---

# check if we can decrypt vault
- block:
    - name: Verify we can decode vault
      no_log: "{{sram_ansible_nolog}}"
      debug:
        var: backup_collector_ssh_key
    - name: Set variable
      set_fact: vault_decrypted=true
  rescue:
    - meta: noop
    - name: Set variable
      set_fact: vault_decrypted=false

- name: Install tmpreaper
  apt:
    name: "tmpreaper"
    state: "present"

- name: Disable tmpreaper cron
  lineinfile:
    path: "/etc/cron.daily/tmpreaper"
    insertafter: "^#!"
    line: "exit 0  # disabled by sram"

- name: Create backup dir {{backup_dir}}
  file:
    path: "{{backup_base}}"
    state: directory
    mode: 0755
    owner: root

# note: individual services can put their backup scripts in the
# {{backup_runparts}} dir in order for them to run daily
- name: Create run-parts dir for backup scripts
  file:
    path: "{{backup_runparts}}"
    state: directory
    mode: 0755
    owner: root

- name: Copy backup upload script
  template:
    src: "upload-backup.sh.j2"
    dest: "{{backup_base}}/upload-backup.sh"
    mode: 0755
    owner: root

- name: Copy ssh key for backup upload
  copy:
    dest: "{{ backup_upload_key }}"
    content: "{{ backup_collector_ssh_key }}"
    owner: "root"
    group: "root"
    mode: "0600"
  no_log: "{{sram_ansible_nolog}}"
  when: backup_collector_ssh_key is defined and vault_decrypted

- name: Add known host for backup host
  known_hosts:
    path: "/etc/ssh/ssh_known_hosts"
    name: "{{ backup_upload_host }}"
    key: "{{ backup_upload_host }} {{ backup_upload_host_key }}"
  when: "backup_upload_host != ''"


- name: Copy backup service files
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
    - scz-backups.service
    - scz-backups.timer
  notify:
    - enable backup job

