---
- name: NTP
  block:

    - name: remove systemd-timesyncd
      apt:
        name: "systemd-timesyncd"
        state: "absent"

    - name: install chrony
      apt:
        name: "chrony"
        state: "present"

    - name: remove ntp
      apt:
        name: "ntp"
        state: "absent"
        purge: true

    - name: install chrony config
      template:
        src: "chrony.conf.j2"
        dest: "/etc/chrony/chrony.conf"
        force: true
      notify:
        - "restart chrony"

    - name: "start chrony"
      systemd:
        name: "chrony.service"
        state: "started"
        enabled: true

  when:
    - "not is_dev"
