---
- name: NTP
  block:

    - name: disable systemd timesyncd
      systemd:
        name: "systemd-timesyncd.service"
        masked: true
        state: "stopped"

    - name: install chrony
      apt:
        name: "chrony"
        state: "present"

    - name: remove ntp
      apt:
        name: "ntp"
        state: "absent"
        purge: true

    - name: install chrony config
      template: src=chrony.conf.j2 dest=/etc/chrony/chrony.conf force=yes
      notify:
        - restart chrony

    - name: "start chrony"
      systemd:
        name: "chrony.service"
        state: "started"
        enabled: true

  when:
    - environment_name!="vm"
