---
- name: "Install required packages"
  apt:
    state: "latest"
    name:
      - "python3-pymysql"
    install_recommends: false

- name: "Add SBS database"
  community.mysql.mysql_db:
    login_host: '{{ sbs_db_host }}'
    login_port: '3306'
    login_user: '{{ sbs_db_admin_user }}'
    login_password: '{{ sbs_db_admin_password }}'
    name: '{{ sbs_db_name }}'
    encoding: 'utf8mb4'
    collation: 'utf8mb4_unicode_ci'
    ca_cert: "/etc/ssl/vm.scz-vm.net.crt"
    check_hostname: false
  notify: "Restart sbs containers"

- name: "Add SBS user"
  community.mysql.mysql_user:
    login_host: '{{ sbs_db_host }}'
    login_port: '3306'
    login_user: '{{ sbs_db_admin_user }}'
    login_password: '{{ sbs_db_admin_password }}'
    name: '{{ item.user }}'
    host: '%'
    password: '{{ item.passwd }}'
    priv: '{{ sbs_db_name }}.*:{{ item.priv }}'
    ca_cert: "/etc/ssl/vm.scz-vm.net.crt"
    check_hostname: false
    column_case_sensitive: "{{ sbs_db_user_column_case_sensitive }}"
  with_items:
    - user: "{{ sbs_db_user }}"
      passwd: "{{ sbs_db_password }}"
      priv: "SELECT,INSERT,DELETE,UPDATE,TRIGGER"
    - user: "{{ sbs_migration_user }}"
      passwd: "{{ sbs_migration_password }}"
      priv: "ALL"
    - user: "{{ sbs_dbbackup_user }}"
      passwd: "{{ sbs_dbbackup_password }}"
      priv: "SELECT"
  no_log: "{{sram_ansible_nolog}}"
  notify: "Restart sbs containers"
