---
- name: "Install packages"
  apt:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "docker-compose"
      - "ansible"

- name: "Fix cgroup v1 for docker"
  lineinfile:
    path: "/etc/default/grub"
    line: >
      GRUB_CMDLINE_LINUX="systemd.legacy_systemd_cgroup_controller=yes
      systemd.unified_cgroup_hierarchy=0"'
    regexp: '^GRUB_CMDLINE_LINUX='
    state: "present"

# TODO:
# - add apache (of nog liever: nginx)
# -
# - add user for ci-runner (draai nu nog als martin)
# - install github action runner
