# install a dummy http server
---
- name: Install nginx
  apt:
    name: "nginx"
    state: "present"


- name: Install NGINX tls config
  lineinfile:
    path: "/etc/nginx/nginx.conf"
    line: "\t{{item.key}} {{item.value}};"
    regexp: '^\s*{{item.key}}'
  with_dict:
    ssl_protocols: "TLSv1.3"
    ssl_prefer_server_ciphers: "off"
  notify: "restart nginx"

- name: install logging config
  copy:
    src: "proxy_log.conf"
    dest: "/etc/nginx/conf.d"
  notify: "restart nginx"

- name: install max request size config
  copy:
    src: "sram_max_size.conf"
    dest: "/etc/nginx/conf.d"
  notify: "restart nginx"

# needs to be changed in this file, can't override lateron
- name: disable gzip to prevent BREACH
  lineinfile:
    path: "/etc/nginx/nginx.conf"
    line: "\tgzip off;"
    regexp: "^\\s*gzip\\s"
  notify: "restart nginx"


- name: Remove upstream nginx default
  file:
    dest: "{{item}}"
    state: "absent"
  with_items:
    - "/etc/nginx/sites-enabled/default"
    - "/etc/nginx/sites-enabled/00-default"
  notify: "restart nginx"

- name: Install our NGINX default file
  template:
    src: "default.j2"
    dest: "/etc/nginx/sites-available/scz-default"
  notify: "restart nginx"

- name: Create symlink to default in /etc/nginx/sites-enabled
  file:
    src: "/etc/nginx/sites-available/scz-default"
    dest: "/etc/nginx/sites-enabled/00-scz-default"
    state: "link"
  notify: "restart nginx"


