---
sudo_groups:
  - "sudo_cont"
log_groups:
  - "log_reader"

ldap_admin_group: ldap_vm

environment_name: vm
environment_string: "SCZ Container"
base_domain: "scz-vm.net"
internal_base_domain: "vm.scz-vm.net"

sram_conf_dir: "/opt/sram"

# externally visible!
hostnames:
  sbs:      sbs.{{base_domain}}
  meta:     meta.{{base_domain}}
  ldap:     ldap.{{base_domain}}
  ldap1:    ldap1.{{base_domain}}
  ldap2:    ldap2.{{base_domain}}
  oidc:     oidc-test.{{base_domain}}
  sp:       sp-test.{{base_domain}}
  idp:      idp-test.{{base_domain}}
  oidc_op:  oidc-op.{{base_domain}}

idp_test_port: 8444
sp_test_port: 82
oidc_test_port: 83
oidc_op_port: 93

loadbalancer:
  - name: "sbs"
    hostname: "{{hostnames.sbs}}"
    protocol: http
    backend_hosts: "{{groups['container_docker1']}}"
    backend_port: 443
    options:
      httpchk: "GET /health"
  - name: "meta"
    hostname: "{{hostnames.meta}}"
    protocol: http
    backend_hosts: "{{groups['container_docker1']}}"
    backend_port: 443
  - name: "client_oidc"
    hostname: "{{hostnames.oidc}}"
    protocol: http
    backend_hosts: "{{groups['client']}}"
    backend_port: "{{oidc_test_port}}"
  - name: "client_sp"
    hostname: "{{hostnames.sp}}"
    protocol: http
    backend_hosts: "{{groups['client']}}"
    backend_port: "{{sp_test_port}}"
  - name: "client_idp"
    hostname: "{{hostnames.idp}}"
    protocol: http
    backend_hosts: "{{groups['client']}}"
    backend_port: "{{idp_test_port}}"
  - name: "client_oidc_op"
    hostname: "{{hostnames.oidc_op}}"
    protocol: http
    backend_hosts: "{{groups['client']}}"
    backend_port: "{{oidc_op_port}}"
  - name: "client_ldap"
    hostname: "{{hostnames.ldap}}"
    protocol: ldap
    frontend_port: 636
    backend_hosts: "{{groups['container_docker1']}}"
    backend_port: 636
  - name: "client_ldap1"
    hostname: "{{hostnames.ldap1}}"
    protocol: ldap
    frontend_port: 636
    backend_hosts: "{{groups['container_docker1']}}"
    backend_port: 636
  - name: "client_ldap2"
    hostname: "{{hostnames.ldap2}}"
    protocol: ldap
    frontend_port: 636
    backend_hosts: "{{groups['container_docker2']}}"
    backend_port: 636
