---
firewall_v4_incoming:
  - name: loadbalancer
    src: "{{lb_ip}}"
    dport:  "{{sbs_server_port}}"
    proto: tcp

containers:
  db: sram-db
  redis: sram-redis
  sbs: sram-sbs
  sbs_server: sram-sbs-server
  ldap: sram-ldap
  metadata: sram-metadata
  pyff: sram-pyff
  plsc: sram-plsc

images:
  db: mariadb:11
  redis: redis:7
  sbs: ghcr.io/surfscz/sram-sbs:main
  sbs_server: ghcr.io/surfscz/sram-sbs-server:main
  ldap: ghcr.io/surfscz/sram-ldap:main
  metadata: ghcr.io/surfscz/sram-metadata:main
  pyff: ghcr.io/surfscz/sram-pyff:main
  plsc: ghcr.io/surfscz/sram-plsc:main

ldap_uri: "ldap://localhost/"
ldap_rids:
  101: ldaps://ldap1.scz-vm.net/
  102: ldaps://ldap2.scz-vm.net/
ldap_hosts:
  ldap1.scz-vm.net: "{{ iprange.lb }}"
  ldap2.scz-vm.net: "{{ iprange.lb }}"

traefik_network: traefik
internal_network: sram


####################################################
## SBS
####################################################
db_host: "docker1.vm.scz-vm.net"
sbs_db_host: "{{ containers.db }}"
sbs_db_admin_user: "{{ db_admin_user }}"
sbs_db_admin_passwd: "{{ db_admin_password }}"

sbs_redis_host: "{{ containers.redis }}"

sbs_base_domain: "{{ hostnames.sbs }}"
sbs_base_url: "https://{{sbs_base_domain}}"
sbs_api_url: "https://{{sbs_base_domain}}/"

sbs_oidc_authz_endpoint: "https://{{ hostnames.oidc_op }}/authorization"
sbs_oidc_token_endpoint: "https://{{ hostnames.oidc_op }}/token"
sbs_oidc_userinfo_endpoint: "https://{{ hostnames.oidc_op }}/userinfo"
sbs_oidc_jwks_endpoint: "https://{{ hostnames.oidc_op }}/jwks.json"
sbs_oidc_redirect_uri: "https://{{ hostnames.sbs }}/api/users/resume-session"
sbs_eduteams_continue_endpoint: "https://{{ hostnames.oidc_op }}/continue"
sbs_oidc_jwt_audience: "https://{{ hostnames.oidc_op }}"

sbs_ldap_url: "ldap://ldap.scz-vm.net/dc=services,dc=vnet"
# entity_id will be replaced run-time in the client
sbs_ldap_bind_account: "cn=admin,dc=entity_id,dc=services,dc=vnet"

sbs_db_tls_cert: "{{wildcard_backend_cert.pub}}"

sbs_mfa_idp_allowed:
  - schac_home: "ci-runner.sram.surf.nl"
    entity_id: "https://idp.scz-vm.net/saml/saml2/idp/metadata.php"

sbs_ssid_identity_providers:
  - schac_home: "ssid.org"
    entity_id: "https://ssid.org"

sbs_notifications_enabled: True
sbs_cron_hour_of_day: "4"
