---
enable_ipv6: true

haproxy:
  custom_dhparam: false
  dhparam_keysize: 2048

http_hosts:
  - "{{base_domain}}"
  - "sbs.{{base_domain}}"
  - "meta.{{base_domain}}"

zabbix_templates_extra:
  - "HAProxy by Zabbix agent"

aclsync_interval_seconds: 30

firewall_v4_incoming:
  - { name: bastion,      src: "{{iprange.bastion}}",  dport:  "22",           proto: tcp }
  - { name: public_http,                               dport:  "80",           proto: tcp }
  - { name: public_https,                              dport: "443",           proto: tcp }
  - { name: vnet,         src: "{{iprange.internal}}", dport: "22,80,443,636", proto: tcp }

