---
firewall_v4_incoming:
  - { name: bastion,      src: "{{iprange.bastion}}",  dport: "22",        proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",       dport: "80",        proto: tcp }
  - { name: vnet,         src: "{{iprange.internal}}", dport: "22,80,443", proto: tcp }

metadata_project_dir: "/opt/metadata"
proxy_hostname: "meta.scz-vm.net"
metadata_registration_authority: "http://federatie.example.org/"

metadata_proxy_frontend_source: "https://proxy.sram.surf.nl/metadata/frontend.xml"
metadata_proxy_backend_source: "https://proxy.sram.surf.nl/metadata/backend.xml"
