---
- name: enable rapportage job
  systemd:
    name: "sram-rapportage.timer"
    enabled: true
    state: "started"
    daemon_reload: true

- name: restart rapportage job
  systemd:
    name: "sram-rapportage.timer"
    enabled: true
    state: "restarted"
    daemon_reload: true
