---
- name: "install python ldap module"
  apt:
    name: "python3-ldap"
    state: "present"

- name: "Create ldap monitor group"
  group:
    name: "{{ldap_monitor_group}}"

- name: "Ensure that ldap_monitor_dir exist"
  file:
    path: "{{ldap_monitor_dir}}"
    state: "directory"
    mode: "0755"

- name: "Ensure that ldap_monitor_dir status exist"
  file:
    path: "{{ldap_monitor_status_dir}}"
    state: "directory"
    owner: "root"
    group: "{{ldap_monitor_group}}"
    mode: "0775"

- name: "Create monitoring script"
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ ldap_monitor_dir }}/{{ item.file }}"
    owner: "root"
    group: "{{ldap_monitor_group}}"
    mode: "{{ item.perm }}"
  with_items:
    - { file: "ldapmonitor.sh", perm: "0750" }
    - { file: "getmonitor.py",  perm: "0755" }


- name: Copy scripts
  copy:
    src: "{{ item }}"
    dest: "{{ ldap_monitor_dir }}/{{ item }}"
    mode: "0755"
  with_items:
    - ldifchecksum.py
    - ldifparser.py

- name: Copy reference
  copy:
    src: "{{inventory_dir}}/files/{{ldap_monitor_reference}}"
    dest: "{{ ldap_monitor_dir }}/{{ldap_monitor_reference}}"

- name: Copy monitor service files
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
    - sram-ldapmonitor.service
    - sram-ldapmonitor.timer
  notify:
    - "enable monitor job"

- name: Copy zabbix agent ldapmonitor key
  template:
    src: sram-ldapmonitor.conf.j2
    dest: "/etc/zabbix/zabbix_agent2.d/sram-ldapmonitor.conf"
  notify: "restart zabbix-agent"
