---
- name: "install python ldap module"
  apt:
    name: "python3-ldap"
    state: "present"

- name: "Ensure that ldap_monitor_dir exist"
  file:
    path: "{{ ldap_monitor_dir }}"
    state: "directory"
    mode: "0755"

- name: "Create ldap_monitor.sh script"
  template:
    src: "ldap_monitor.sh.j2"
    dest: "{{ ldap_monitor_dir }}/ldap_monitor.sh"
    mode: "0755"

- name: Copy ldifchecksum.py script
  copy:
    src: ldifchecksum.py
    dest: "{{ ldap_monitor_dir }}/ldifchecksum.py"
    mode: "0755"

- name: Copy monitor service files
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
    - "ldap_monitor.service"
    - "ldap_monitor.timer"
  notify:
    - "enable monitor job"
