#!/bin/sh
. bin/activate
#satosa-saml-metadata --dir metadata --split-frontend --split-backend proxy_conf.yaml certs/https.key certs/https.crt
satosa-saml-metadata --dir metadata proxy_conf.yaml certs/signing.key certs/signing.crt
