#!/bin/bash
set -e

LOGDIR=logs
LOG=$LOGDIR/aws-bhr-deploy.$(date '+%Y%m%d_%H%M').log

CMD="ansible-playbook provision.yml \
    -i ./environments/aws_bhr/inventory \
    --limit=bhr \
    --diff \
    "$@"
"

CMD=$( echo $CMD | sed 's/\s\+/ /g' )

echo "Deploying to AWS..."
echo "Log file: $LOG"
echo "Will execute: $CMD"

stdbuf --output=0 --error=0 $CMD |& tee "$LOG"

exit 0
