---
collections:
  - name: "community.mysql"
    version: ">=1.3.0,<1.4"
  - name: "community.general"
    version: ">=6.0.0,<6.1"
  - name: "community.crypto"
    version: ">=1.7,<2.0"
  - name: "community.zabbix"
    version: "<2.0"
  - name: "ansible.posix"
    version: ">=1.3.0,<1.4"
  - name: "ansible.utils"
    version: ">=2.10.0,<3.0"

roles:
  - name: "monolithprojects.github_actions_runner"
