---
collections:
  - name: "community.mysql"
    version: ">=1.3.0,<1.4"
  - name: "community.general"
    version: ">=3.7.0,<3.8"
  - name: "community.crypto"
    version: ">=1.7,<2.0"
  - name: "git+https://github.com/ansible-collections/community.zabbix.git"
    version: "main"
  - name: "ansible.posix"
    version: ">=1.3.0,<1.4"
  - name: "ansible.utils"
    version: ">=2.5.0,<2.6.0"
