---
collections:
  - name: "community.mysql"
    version: ">=1.3.0,<1.4"
  - name: "community.general"
    version: ">=2.4.0,<3.0"
  - name: "community.crypto"
    version: ">=1.7,<2.0"
  - name: "community.zabbix"
    version: ">=1.4.0,<1.5"
