---
collections:
  - name: "community.mysql"
    version: ">=3.9,<4.0"
  - name: "community.general"
    version: ">=9.1,<10.0"
  - name: "community.crypto"
    version: ">=2.20,<3.0"
  - name: "community.zabbix"
    version: ">=3.3,<4.0"
  - name: "community.docker"
    version: ">=3.10,<4.0"
  - name: "ansible.posix"
    version: ">=1.5,<2.0"
  - name: "ansible.utils"
    version: ">=5.0,<6.0"

roles:
  - name: "monolithprojects.github_actions_runner"
    version: "1.21.1"
    src: "https://github.com/MonolithProjects/ansible-github_actions_runner"
