#!/bin/bash
set -e

if [ ! -f docker/ansible_key.pub ]; then
    echo "No ansible key found"
    ssh-keygen -f docker/ansible_key -N ""
fi

# Build single docker image before docker-compose starts
if [ -z "$REENTRANT" ]; then
    scz_image=$(docker image list scz-base -q)
    if [ -z "$scz_image" ]
    then
        echo "Building docker image"
        time docker build -t scz-base --target=scz-base --force-rm docker/
    else
        echo "Docker image found"
    fi
fi

# Bring up the VMs if they're not running
echo "Bringing docker containers up"
./docker/docker-compose.yml.py > ./docker/docker-compose.yml
time docker-compose -f docker/docker-compose.yml up -d

echo "Starting ansible"
time \
ansible-playbook provision.yml \
    -i ./environments/vm/inventory \
    --extra-vars="secrets_file=environments/vm/secrets/all.yml" \
    --vault-password-file=secret_vm \
    $@

# restart proxy to reload all metadata (chicken finds eggs)
ansible -i ./environments/vm/inventory -m command -a 'systemctl restart pyff' proxy >> /dev/null 2>&1

exit 0
