#!/bin/bash
set -e

ENV=test
LOGDIR=logs
LOG=$LOGDIR/surf-deploy.$(date '+%Y%m%d_%H%M').log

mkdir -p $LOGDIR || true


if [ "$1" = "--pilot" ]
then
	ENV=pilot
	EXTRA="${EXTRA} --ask-vault-pass"
	shift
fi

CMD="ansible-playbook provision.yml \
		-i ./environments/surf/inventory \
		--limit=${ENV} \
		--ask-become \
		${EXTRA} \
		"$@"
"

CMD=$( echo $CMD | sed 's/\s\+/ /g' )

echo "Deploying to SURfscz $ENV..."
echo "Log file: $LOG"
echo "Will execute: $CMD"

stdbuf --output=0 --error=0 $CMD |& tee "$LOG"

exit 0


