#!/bin/bash
# run command on all specified hosts
set -e

DIR=$(dirname $0)
cd $DIR

ARG=${1#--}
if [ "$ARG" = "bhr" -o "$ARG" = "beheer" ]
then
    ENV=bhr
    CONFDIR=./environments/aws_bhr/
elif [ "$ARG" = "prd" -o "$ARG" = "prod" ]
then
    ENV=prd
    CONFDIR=./environments/aws_prd/
elif [ "$ARG" = "acc" ]
then
    ENV=acc
    CONFDIR=./environments/aws_acc/
elif [ "$ARG" = "tst" -o "$ARG" = "test" ]
then
    ENV=tst
    CONFDIR=./environments/aws_tst/
else
    echo "syntax: $0 <bhr|tst|acc|pord> [-r] <selector> <command>"
    echo "Please specify an environment to deploy (bhr, prod, acc, test)"
    exit 1
fi
shift

yes=0
if [ "$1" = "-y" ]
then
	yes=1
	shift
fi

root=
if [ "$1" = "-r" ]
then
	root="--become --ask-become-pass"
	shift
fi

if [ "$#" -lt 2 ]
then
	echo "Please specify a host selector (i.e., 'all') and a command"
	exit 1
fi

host=$1
cmd=$2

if [ "$yes" == "0" ]
then
    echo -n "Will run '$cmd' on host '$ENV/$host'" >&2
    if [ -n "$root" ]
    then
        echo -n " as root" >&2
    fi
    echo >&2
    echo -n "Press enter to continue"  >&2
    read
    echo
fi

ansible -v -i ${CONFDIR}/inventory $root "$host" -m command -a "$cmd"

exit 0
