#!/bin/bash
set -e

ENV=test
LOGDIR=logs
LOG=$LOGDIR/surf-deploy.$(date '+%Y%m%d_%H%M').log

mkdir -p $LOGDIR || true

# first check that deploy and deploy-surf are using the same version
if ! git diff-index --quiet HEAD --
then
	echo "SCZ-deploy repo is not clean:"
	git status
	exit 1
fi
branch_deploy=$(git symbolic-ref --short HEAD)
cd environments/surf
if ! git diff-index --quiet HEAD --
then
	echo "SCZ-deploy-surf repo is not clean:"
	git status
	exit 1
fi
branch_surf=$(git symbolic-ref --short HEAD)
cd ../..
if [ "$branch_deploy" != "$branch_surf" ]
then
	echo "Deploy branch is '$branch_deploy', but surf branch is '$branch_surf', exiting"
	exit 1
fi


if [ "$1" = "--pilot" ]
then
	ENV=pilot
	EXTRA="${EXTRA} --ask-vault-pass"
	shift
fi

CMD="ansible-playbook provision.yml \
		-i ./environments/surf/inventory \
		--limit=${ENV} \
		--ask-become \
		${EXTRA} \
		"$@"
"

CMD=$( echo $CMD | sed 's/\s\+/ /g' )

echo "Deploying to SURfscz $ENV..."
echo "Log file: $LOG"
echo "Will execute: $CMD"

stdbuf --output=0 --error=0 $CMD |& tee "$LOG"

exit 0


