---
- name: renew letsencrypt certificates
  command:
    cmd: >
      /usr/bin/certbot certonly --noninteractive
                                {% if letsencrypt_server is defined %}
                                  --server '{{letsencrypt_server}}'
                                {% endif %}
                                --keep-until-expiring
                                --renew-with-new-domains
                                --domains={{item}}
  register: result
  changed_when: "'Certificate is saved at' in result.stdout"
  with_items: "{{ letsencrypt_hosts }}"
  when: "letsencrypt_enabled and letsencrypt_hosts is defined"
  notify: "renew letsencrypt certificates again"

# we need to renew directly in order to run the post renewal hooks...
- name: renew letsencrypt certificates again
  command:
    cmd: >
      /usr/bin/certbot renew --noninteractive
                             {% if letsencrypt_server is defined %}
                               --server '{{letsencrypt_server}}'
                             {% endif %}
                             --no-random-sleep-on-renew
                             --force-renewal
                             --cert-name={{item}}
  register: result
  changed_when: '"Congratulations, all renewals succeeded" in result.stdout'
  when: "letsencrypt_enabled and letsencrypt_hosts is defined"
  with_items: "{{ letsencrypt_hosts }}"
