---
- name: "enable backup sync job"
  systemd:
    name: "sram-backup-sync.timer"
    enabled: true
    state: "started"
    daemon_reload: true

- name: "restart zabbix-agent"
  systemd:
    name: "zabbix-agent2.service"
    state: "restarted"
