---
ldap_monitor_dir: "/opt/ldapmonitor"
ldap_monitor_status_dir: "{{ldap_monitor_dir}}/status"
ldap_monitor_file: "{{ldap_monitor_status_dir}}/ldap-info.txt"
ldap_monitor_group: "sram-ldapmonitor"
ldap_monitor_service: "https://cloud"
ldap_monitor_password: "changethispassword"
ldap_monitor_reference: "ldap_cloud_ref"
