---
ldap_monitor_dir: "/opt/ldapmonitor"
ldap_monitor_status_dir: "{{ldap_monitor_dir}}/status"
ldap_monitor_file: "{{ldap_monitor_status_dir}}/ldap-info.txt"
ldap_monitor_group: "sram-ldapmonitor"
ldap_monitor_service: "110751a9-b0b4-4c7d-8728-f323101147c0"
ldap_monitor_password: "changethispassword"
ldap_monitor_reference: "ldap_cloud_ref"
