---
#########################################################
## Demop app
#########################################################
- name: Create html dir
  file:
    path: "{{testidp_html_dir}}"
    state: "directory"
    mode: "0755"

#########################################################
## SAML IdP
#########################################################
- include_role:
    name: "simplesamlphp"
    public: true
  vars:
    simplesaml_name: "{{testidp_name}}"
    simplesaml_user: "{{testidp_user}}"
    simplesaml_group: "{{testidp_group}}"
    simplesaml_project_dir: "{{testidp_dir}}"

- name: SimpleSaml configuration (templates)
  template:
    src: "{{item}}.j2"
    dest: "{{ simplesaml_project_dir }}/config/{{item}}"
  with_items:
    - "saml20-idp-hosted.php"

- name: SimpleSaml configuration (copy)
  template:
    src: "{{item}}.j2"
    dest: "{{ simplesaml_project_dir }}/config/{{item}}"
  with_items:
    - "saml20-idp-remote.php"
    - "saml20-sp-remote.php"

- name: Link SimpleSaml configuration
  file:
    src: "{{ simplesaml_project_dir }}/config/{{item.key}}"
    path: "{{ simplesaml_project_dir }}/simplesaml/{{item.value}}/{{item.key}}"
    state: "link"
    force: true
  with_dict:
    saml20-idp-hosted.php: "metadata"
    saml20-idp-remote.php: "metadata"
    saml20-sp-remote.php: "metadata"

- name: Generate a SAML signing certificate
  command:
    cmd: >
      openssl req -x509 -newkey rsa:2048 -sha256 -days 36500 -nodes
              -keyout saml.key -out saml.pem
              -subj '/CN=simpelsamlphp/'
    chdir: "{{simplesaml_cert_dir}}"
    creates: "{{simplesaml_cert_dir}}/saml.pem"

- name: Set permissions for keys
  file:
    path: "{{simplesaml_cert_dir}}/saml.key"
    mode: "0640"
    group: "{{testidp_group}}"

#########################################################
## nginx
#########################################################
- include_role:
    name: "nginx"

- include_role:
    name: "letsencrypt"
    public: true
  vars:
    letsencrypt_hosts: [ "{{testidp_hostname}}",  "{{testidp2_hostname}}" ]
    letsencrypt_server: "{{ bhr13_acme_server_url }}"
    letsencrypt_eab: true
    letsencrypt_eab_keyid: "{{ bhr13_acme_eab_keyid }}"
    letsencrypt_eab_hmac: "{{ bhr13_acme_hmac_key }}"


- name: Install nginx config
  template:
    src: "{{ item.src }}"
    dest: "/etc/nginx/sites-enabled/{{ item.dest }}"
  notify: "restart nginx"
  with_items:
    - { "src": "nginx1.conf.j2", "dest": "01-sram-testidp1.conf" }
    - { "src": "nginx2.conf.j2", "dest": "01-sram-testidp2.conf" }

- name: Restart nginx after certificate rollover
  copy:
    content: |
      #!/bin/sh
      echo "restarting nginx"
      /usr/bin/systemctl reload nginx.service
      exit 0
    dest: "{{letsencrypt_hooks}}/sram-nginx.sh"
    mode: "0755"
