---
- name: "enable scimserver job"
  systemd:
    name: "sram-scimserver-{{ item.key }}.service"
    enabled: true
    state: "restarted"
    daemon_reload: true
  with_dict: "{{ scim_monitor_config }}"

- name: "restart zabbix-agent"
  systemd:
    name: "zabbix-agent2.service"
    state: "restarted"
