---
- name: "enable scimserver job"
  systemd:
    name: "sram-scimserver.service"
    enabled: true
    state: "restarted"
    daemon_reload: true

- name: "restart zabbix-agent"
  systemd:
    name: "zabbix-agent2.service"
    state: "restarted"
