---
surfstar_idp_name: "surfstar-idp"
surfstar_idp_user: "surfstar-idp"
surfstar_idp_group: "surfstar-idp"
surfstar_idp_dir: "/opt/{{surfstar_idp_name}}"
surfstar_idp_html_dir: "{{surfstar_idp_dir}}/html"
surfstar_idp_hostname: "test-idp.lab.surf.nl"
