---
- name: "Zabbix repo: install gpg key"
  apt_key:
    id: "A1848F5352D022B9471D83D0082AB56BA14FE591"
    url: "http://repo.zabbix.com/zabbix-official-repo.key"

- name: "Zabbix repo: install source"
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/6.4/debian {{debian_dist}} main"
    state: present

- name: "Ensure that packages are installed"
  apt:
    name: "zabbix-agent2"
    state: "latest"
    install_recommends: false

- name: "Make sure the zabbix user can read journald entries"
  ansible.builtin.user:
    name: zabbix
    groups: systemd-journal
    append: true
  notify: "restart zabbix-agent"

- name: "PSK handling"
  include_tasks: "psk.yml"
  when: "not is_docker"

- name: "Default configuration"
  template:
    src: "zabbix-agent2.conf.j2"
    dest: "/etc/zabbix/zabbix_agent2.d/zabbix-sram.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  when: "not is_docker"
  notify: "restart zabbix-agent"

# - name: "Count upgradeable packages"
#   copy:
#     src: "{{item}}"
#     dest: "/usr/local/sbin/{{item}}"
#     mode: "0755"
#   with_items:
#     - "count_upgradeable"
#     - "restart_kernel"
#     - "restart_services"

- name: "Zabbix registration"
  vars:
    ansible_network_os: "community.zabbix.zabbix"
    ansible_connection: "httpapi"
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: "{{zabbix_validate_certs}}"
    ansible_host: "{{zabbix_host}}"
    ansible_zabbix_url_path: '/'
    ansible_user: "{{zabbix_api_user}}"
    ansible_httpapi_pass: "{{zabbix_api_password}}"
  when: "not is_docker"
  become: false
  throttle: 1
  block:

    - name: "Register host group"
      community.zabbix.zabbix_group:
        host_groups:
          - "sram"
          - "sram-{{environment_name}}"
        state: "present"

    # dumb workaround: the zabbix_host module doesn't actually update the PSK when
    # it has changed;  So remove and recreate the host if that happens.
    - name: "Delete host"
      community.zabbix.zabbix_host:
        host_name: "{{inventory_hostname}}"
        state: "absent"
      when: "psk_file_write.changed"  # noqa: no-handler

    - name: "Register host"
      community.zabbix.zabbix_host:
        host_name: "{{inventory_hostname}}"
        host_groups:
          - "sram"
          - "sram-{{environment_name}}"
        tags:
          - tag: "sram-env"
            value: "{{environment_name}}"
        link_templates: "{{ zabbix_templates_default|list + zabbix_templates_extra|list }}"
        status: "enabled"
        state: "present"
        interfaces:
          - type: "1"
            main: "1"
            useip: "1"
            ip: "{{ansible_default_ipv4.address}}"
            dns: ""
            port: "10050"
      register: "host_register"

    - name: "Set PSK setting for host"
      community.zabbix.zabbix_host:
        host_name: "{{inventory_hostname}}"
        tls_psk_identity: "{{inventory_hostname}}"
        tls_psk: "{{zabbix_agent_psk}}"
        tls_accept: "2"
        tls_connect: "2"
      become: false
      when: "psk_file_write.changed or host_register.changed"

