---
- name: "Zabbix repo: install gpg key"
  apt_key:
    id: "A1848F5352D022B9471D83D0082AB56BA14FE591"
    url: "http://repo.zabbix.com/zabbix-official-repo.key"

- name: "Zabbix repo: install source"
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/5.4/debian bullseye main"
    state: present

- name: "Ensure that packages are installed"
  apt:
    name: "zabbix-agent2"
    state: "present"
    install_recommends: false

- name: "Make sure the zabbix user can read journald entries"
  ansible.builtin.user:
    name: zabbix
    groups: systemd-journal
    append: true
  notify: "restart zabbix-agent"

- include_tasks: "psk.yml"

- name: "Default configuration"
  template:
    src: "zabbix-agent2.conf.j2"
    dest: "/etc/zabbix/zabbix_agent2.d/zabbix-sram.conf"
  notify: "restart zabbix-agent"

# - name: "Count upgradeable packages"
#   copy:
#     src: "{{item}}"
#     dest: "/usr/local/sbin/{{item}}"
#     mode: "0755"
#   with_items:
#     - "count_upgradeable"
#     - "restart_kernel"
#     - "restart_services"

- block:
    - name: Set connection specific variables
      #delegate_to: "{{zabbix_server}}"
      set_fact:
        ansible_network_os: "community.zabbix.zabbix"
        ansible_connection: "httpapi"
        ansible_user: "{{zabbix_api_user}}"
        ansible_httpapi_pass: "{{zabbix_api_password}}"
        ansible_httpapi_port: 443
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: "{{zabbix_validate_certs}}"

    - name: "Register host group"
      delegate_to: "{{zabbix_server}}"
      connection: httpapi
      throttle: 1
      community.zabbix.zabbix_group:
        host_groups:
          - "sram"
          - "sram-{{environment_name}}"
        state: "present"
      become: false

    - name: "Register host"
      delegate_to: "{{zabbix_server}}"
      community.zabbix.zabbix_host:
        host_name: "{{inventory_hostname}}"
        host_groups:
          - "sram"
          - "sram-{{environment_name}}"
        tags:
          - tag: "sram-env"
            value: "{{environment_name}}"
        link_templates: "{{ zabbix_templates_default|list + zabbix_templates_extra|list }}"
        tls_accept: "2"
        tls_connect: "2"
        status: "enabled"
        state: "present"
        interfaces:
          - type: "1"
            main: "1"
            useip: "1"
            ip: "{{ansible_default_ipv4.address}}"
            dns: ""
            port: "10050"

    - name: "Set PSK setting for host"
      delegate_to: "{{zabbix_server}}"
      community.zabbix.zabbix_host:
        host_name: "{{inventory_hostname}}"
        tls_psk_identity: "{{inventory_hostname}}"
        tls_psk: "{{zabbix_agent_psk}}"
      when: "psk_file_write.changed"

  when: "not is_docker"
