---

- name: install PyFF
  import_role:
    name: "pyff"

- name: Write source metadata certificate
  template:
    src: "feed.xrd.j2"
    dest: "{{metadata_idps_xrd}}"
  notify: "run pyff-metadata job"

- name: Create metadata source directory
  file:
    path: "{{ metadata_source_dir }}"
    state: "directory"
    mode: "0755"
    owner: "root"

- name: install IdP metadata
  copy:
    content: "{{item.metadata}}"
    dest: "{{ metadata_source_dir }}/{{item.name}}.xml"
    mode: "0644"
    owner: "root"
  with_items: "{{ metadata_idps_files }}"
  notify:
    - "run pyff-metadata job"

- name: Create pyFF mdq configuration
  template:
    src: "{{item}}.j2"
    dest: "{{ pyff_env_dir }}/{{item}}"
  with_items:
    - "idps_feed.fd"
    - "frontend_feed.fd"
    - "backend_feed.fd"
    - "feeds.sh"
    - "transform.xslt"
  become: "yes"
  become_user: "pyff"
  notify: "run pyff-metadata job"

- name: Make feeds.sh executable
  file:
    path: "{{ pyff_env_dir }}/feeds.sh"
    state: "file"
    mode: "0755"

- name: Create pyFF systemd job timer
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
    - "pyff-metadata.service"
    - "pyff-metadata.timer"
  notify:
    - "enable pyff-metadata job"
    - "run pyff-metadata job"
