---
- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
  listen: "restart rsyslog"

- name: systemd daemon-reload
  systemd:
    name: slapd
    daemon_reload: yes

- name: restart LDAP
  systemd:
    name: slapd
    state: restarted
    enabled: true
    daemon-reload: true

