---
#########################################################
## SAML SP
#########################################################
- include_role:
    name: "simplesamlphp"
    public: true
  vars:
    simplesaml_name: "{{ssphp_name}}"
    simplesaml_user: "{{ssphp_user}}"
    simplesaml_group: "{{ssphp_group}}"
    simplesaml_project_dir: "{{ssphp_dir}}"

- name: Enable exampleauth module
  ansible.builtin.copy:
    content: ''
    dest: "{{ ssphp_dir }}/simplesaml/modules/exampleauth/enable"

- name: SimpleSaml configuration
  template:
    src: "{{item}}.j2"
    dest: "{{ ssphp_dir }}/config/{{item}}"
  with_items:
    - "saml20-idp-hosted.php"
    - "saml20-sp-remote.php"

- name: Link SimpleSaml configuration
  file:
    src: "{{ ssphp_dir }}/config/{{item.key}}"
    path: "{{ ssphp_dir }}/simplesaml/{{item.value}}/{{item.key}}"
    state: "link"
    force: true
  with_dict:
    saml20-idp-hosted.php: "metadata"
    saml20-sp-remote.php: "metadata"

- name: Copy self-signed Token signing cert key
  copy:
    content: "{{client_saml_cert.priv}}"
    dest: "{{simplesaml_cert_dir}}/server.key"
    group: "{{ssphp_group}}"
    mode: "0640"
  no_log: "{{sram_ansible_nolog}}"
  notify: "restart php-fpm"

- name: Copy self-signed Token signing cert
  copy:
    content: "{{client_saml_cert.pub}}"
    dest: "{{simplesaml_cert_dir}}/server.crt"
  notify: "restart php-fpm"


#########################################################
## OIDC RP
#########################################################
- name: Ensure that packages are installed
  apt:
    name:
      - "composer"
    state: "present"

- name: Create directories
  file:
    path: "{{ item }}"
    state: "directory"
    mode: "0755"
  with_items:
    - "{{ rp_jumbojett_dir }}"
    - "{{ rp_docroot_dir }}"

- name: Install JumboJett OIDC PHP module
  community.general.composer:
    command: "require"
    arguments: "jumbojett/openid-connect-php"
    working_dir: "{{ rp_jumbojett_dir}}"
  notify: "restart php-fpm"

- name: Create RP files
  template:
    src: "index.php.j2"
    dest: "{{ rp_docroot_dir }}/index.php"
    mode: "0644"
  notify: "restart php-fpm"


#########################################################
## nginx
#########################################################
- include_role:
    name: "nginx"

- name: Install nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/sites-enabled/01-sram-ssphp.conf"
  notify: "restart nginx"
