---
- name: systemd daemon-reload
  systemd:
    daemon_reload: true

- name: restart journal-remote
  systemd:
    name: "sram-remotejournal-{{item.key}}.service"
    state: "restarted"
  with_dict: "{{journal_upload_ports}}"

- name: restart journal-remote-socket
  systemd:
    name: "sram-remotejournal-{{item.key}}.socket"
    state: "restarted"
    enabled: true
  with_dict: "{{journal_upload_ports}}"
