---
- name: systemd daemon-reload
  systemd:
    daemon_reload: true

- name: restart journal-remote
  systemd:
    name: "sram-remotejournal-{{item.key}}.service"
    state: "restarted"
  with_dict: "{{journal_remote_types}}"

- name: restart journal-remote-socket
  systemd:
    name: "sram-remotejournal-{{item.key}}.socket"
    state: "restarted"
    enabled: true
  with_dict: "{{journal_remote_types}}"

- name: enable vacuum job
  systemd:
    name: "sram-vacuum-journal.timer"
    enabled: true
    state: "started"
    daemon_reload: true

- name: "restart zabbix-agent"
  systemd:
    name: "zabbix-agent2.service"
    state: "restarted"
