---
- name: enable sram_contacts job
  systemd:
    name: "sram-contacts-{{ item }}.timer"
    enabled: true
    state: "restarted"
    daemon_reload: true
  loop: "{{ tools_contacts_environments.keys() }}"

