DROP DATABASE sbs;
CREATE DATABASE sbs DEFAULT CHARACTER SET utf8;
CREATE DATABASE sbs_test DEFAULT CHARACTER SET utf8;
CREATE USER 'sbs'@'localhost' IDENTIFIED BY 'sbs';
GRANT ALL PRIVILEGES ON *.* TO 'sbs'@'%' WITH GRANT OPTION;
