---
- name: restart WebSSO daemon
  systemd:
    name: "websso-daemon"
    state: "restarted"
    enabled: true
    daemon_reload: true

- name: restart nginx
  service:
    name: nginx
    state: restarted
