#!/usr/bin/env bash

# Copyright (C) 2015-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2015-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

# Check if specified LDAP schema file is loaded in the local slapd cn=config
# database. If not, try loading it in the server.


set -o nounset -o pipefail -o errexit

schema_file="${1}"

if [ -z "${schema_file}" ] ; then
    printf "Error: You need to specify schema file to load\\n" && exit 1
fi

if [ ! -e "${schema_file}" ] ; then
    printf "Error: %s does not exist\\n" "${schema_file}" && exit 1
fi

if [ ! -r "${schema_file}" ] ; then
    printf "Error: %s is unreadable\\n" "${schema_file}" && exit 1
fi

# The schema file is already converted, we can deal with them directly
if [[ "${schema_file}" == *.ldif ]] ; then

    # Try installing the schema in the database
    ldapmodify -c -Y EXTERNAL -H ldapi:/// -f "${schema_file}"

fi
