---
debian_dist: 'bullseye'

deb_host: >-
  {% if is_aws | default(false) -%}
    http://cdn-aws.deb.debian.org/debian
  {%- else -%}
    http://deb.debian.org/debian
  {%- endif %}
debian:
  mirror: "{{ deb_host }}"
  security_mirror: "{{ deb_host }}-security"
