---
firewall_v4_incoming:
  - name: loadbalancer
    src: "{{lb_ip}}"
    dport:  "{{sbs_server_port}}"
    proto: tcp

sbs_num_workers: 2

sbs_urn_namespace: "urn:mace:surf.nl:x-sram-ci"
sbs_eppn_scope: "ci-runner.sram.surf.nl"

sbs_oidc_authz_endpoint: "https://{{ hostnames.oidc_op }}/saml2sp/OIDC/authorization"
sbs_oidc_token_endpoint: "https://{{ hostnames.oidc_op }}/OIDC/token"
sbs_oidc_userinfo_endpoint: "https://{{ hostnames.oidc_op }}/OIDC/userinfo"
sbs_oidc_jwks_endpoint: "https://{{ hostnames.oidc_op }}/OIDC/jwks"
sbs_oidc_redirect_uri: "https://{{ hostnames.sbs }}/api/users/resume-session"
sbs_oidc_jwt_audience: "https://{{ hostnames.oidc_op }}"
sbs_eduteams_continue_endpoint: "https://proxy.acc.sram.eduteams.org/continue"
sbs_eb_continue_endpoint: "https://engine.(.*)surfconext.nl(.*)"
sbs_oidc_verify_peer: False
sbs_oidc_scopes:
  - openid
  - profile
  - eduperson_scoped_affiliation
  - voperson_external_affiliation
  - email
  - ssh_public_key
  - eduperson_orcid
  - uid
  - voperson_external_id
  - eduperson_entitlement
  - eduperon_assurance
  - eduperson_principal_name
  - voperson_id

sbs_manage_base_enabled: False
sbs_manage_base_url: "https://manage.test2.surfconext.nl"
sram_rp_entity_id: "sbs.test2.sram.surf.nl"
sbs_manage_verify_peer: False

sbs_ldap_url: "ldap://ldap.scz-vm.net/dc=services,dc=vnet"
# entity_id will be replaced run-time in the client
sbs_ldap_bind_account: "cn=admin,dc=entity_id,dc=services,dc=vnet"

sbs_db_tls_cert: "{{wildcard_backend_cert.pub}}"
sbs_db_admin_user: "{{ db_admin_user }}"
sbs_db_admin_password: "{{ db_admin_password }}"

sbs_cron_hour_of_day: "4"
sbs_seed_allowed: True
sbs_api_keys_enabled: True
sbs_feedback_enabled: True
sbs_audit_trail_notifications_enabled: True
sbs_send_exceptions: False
sbs_send_js_exceptions: False
sbs_second_factor_authentication_required: False
sbs_totp_token_name: "SRAM-CI"
sbs_notifications_enabled: True
sbs_impersonation_allowed: True
sbs_admin_platform_backdoor_totp: True
sbs_past_dates_allowed: True
sbs_mock_scim_enabled: True
sbs_swagger_enabled: True
sbs_log_to_stdout: True

sbs_mfa_idp_allowed:
  - schac_home: "ci-runner.sram.surf.nl"
    entity_id: "https://idp.ci-runner.sram.surf.nl/saml/saml2/idp/metadata.php"

sbs_ssid_identity_providers:
  - schac_home: "ssid.org"
    entity_id: "https://ssid.org"

sbs_encryption_key: secret
