PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version));
INSERT INTO "oc_migrations" VALUES('core','13000Date20170705121758');
INSERT INTO "oc_migrations" VALUES('core','13000Date20170718121200');
INSERT INTO "oc_migrations" VALUES('core','13000Date20170814074715');
INSERT INTO "oc_migrations" VALUES('core','13000Date20170919121250');
INSERT INTO "oc_migrations" VALUES('core','13000Date20170926101637');
INSERT INTO "oc_migrations" VALUES('core','14000Date20180129121024');
INSERT INTO "oc_migrations" VALUES('core','14000Date20180404140050');
INSERT INTO "oc_migrations" VALUES('core','14000Date20180516101403');
INSERT INTO "oc_migrations" VALUES('core','14000Date20180518120534');
INSERT INTO "oc_migrations" VALUES('core','14000Date20180522074438');
INSERT INTO "oc_migrations" VALUES('core','14000Date20180626223656');
INSERT INTO "oc_migrations" VALUES('core','14000Date20180710092004');
INSERT INTO "oc_migrations" VALUES('core','14000Date20180712153140');
INSERT INTO "oc_migrations" VALUES('core','15000Date20180926101451');
INSERT INTO "oc_migrations" VALUES('core','15000Date20181015062942');
INSERT INTO "oc_migrations" VALUES('core','15000Date20181029084625');
INSERT INTO "oc_migrations" VALUES('dav','1004Date20170825134824');
INSERT INTO "oc_migrations" VALUES('dav','1004Date20170919104507');
INSERT INTO "oc_migrations" VALUES('dav','1004Date20170924124212');
INSERT INTO "oc_migrations" VALUES('dav','1004Date20170926103422');
INSERT INTO "oc_migrations" VALUES('dav','1005Date20180413093149');
INSERT INTO "oc_migrations" VALUES('dav','1005Date20180530124431');
INSERT INTO "oc_migrations" VALUES('dav','1006Date20180619154313');
INSERT INTO "oc_migrations" VALUES('dav','1006Date20180628111625');
INSERT INTO "oc_migrations" VALUES('dav','1008Date20181030113700');
INSERT INTO "oc_migrations" VALUES('dav','1008Date20181105104826');
INSERT INTO "oc_migrations" VALUES('dav','1008Date20181105104833');
INSERT INTO "oc_migrations" VALUES('dav','1008Date20181105110300');
INSERT INTO "oc_migrations" VALUES('dav','1008Date20181105112049');
INSERT INTO "oc_migrations" VALUES('dav','1008Date20181114084440');
INSERT INTO "oc_migrations" VALUES('activity','2006Date20170808154933');
INSERT INTO "oc_migrations" VALUES('activity','2006Date20170808155040');
INSERT INTO "oc_migrations" VALUES('activity','2006Date20170919095939');
INSERT INTO "oc_migrations" VALUES('activity','2007Date20181107114613');
INSERT INTO "oc_migrations" VALUES('activity','2008Date20181011095117');
INSERT INTO "oc_migrations" VALUES('twofactor_backupcodes','1002Date20170607104347');
INSERT INTO "oc_migrations" VALUES('twofactor_backupcodes','1002Date20170607113030');
INSERT INTO "oc_migrations" VALUES('twofactor_backupcodes','1002Date20170919123342');
INSERT INTO "oc_migrations" VALUES('twofactor_backupcodes','1002Date20170926101419');
INSERT INTO "oc_migrations" VALUES('twofactor_backupcodes','1002Date20180821043638');
CREATE TABLE oc_appconfig (appid VARCHAR(32) DEFAULT '' NOT NULL, configkey VARCHAR(64) DEFAULT '' NOT NULL, configvalue CLOB DEFAULT NULL, PRIMARY KEY(appid, configkey));
INSERT INTO "oc_appconfig" VALUES('core','installedat','1548317950.5791');
INSERT INTO "oc_appconfig" VALUES('core','lastupdatedat','1548317950.6304');
INSERT INTO "oc_appconfig" VALUES('core','vendor','nextcloud');
INSERT INTO "oc_appconfig" VALUES('comments','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('comments','types','logging');
INSERT INTO "oc_appconfig" VALUES('comments','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('survey_client','installed_version','1.3.0');
INSERT INTO "oc_appconfig" VALUES('survey_client','types','');
INSERT INTO "oc_appconfig" VALUES('survey_client','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('password_policy','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('password_policy','types','');
INSERT INTO "oc_appconfig" VALUES('password_policy','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('dav','installed_version','1.8.1');
INSERT INTO "oc_appconfig" VALUES('core','public_webdav','dav/appinfo/v1/publicwebdav.php');
INSERT INTO "oc_appconfig" VALUES('dav','types','filesystem');
INSERT INTO "oc_appconfig" VALUES('dav','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('lookup_server_connector','installed_version','1.3.0');
INSERT INTO "oc_appconfig" VALUES('lookup_server_connector','types','authentication');
INSERT INTO "oc_appconfig" VALUES('lookup_server_connector','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('logreader','installed_version','2.0.0');
INSERT INTO "oc_appconfig" VALUES('logreader','types','');
INSERT INTO "oc_appconfig" VALUES('logreader','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('files_trashbin','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('files_trashbin','types','filesystem,dav');
INSERT INTO "oc_appconfig" VALUES('files_trashbin','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('files_texteditor','installed_version','2.7.0');
INSERT INTO "oc_appconfig" VALUES('files_texteditor','types','');
INSERT INTO "oc_appconfig" VALUES('files_texteditor','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('firstrunwizard','installed_version','2.4.0');
INSERT INTO "oc_appconfig" VALUES('firstrunwizard','types','logging');
INSERT INTO "oc_appconfig" VALUES('firstrunwizard','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('activity','installed_version','2.8.2');
INSERT INTO "oc_appconfig" VALUES('activity','types','filesystem');
INSERT INTO "oc_appconfig" VALUES('activity','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('notifications','installed_version','2.3.0');
INSERT INTO "oc_appconfig" VALUES('notifications','types','logging');
INSERT INTO "oc_appconfig" VALUES('notifications','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('oauth2','installed_version','1.3.0');
INSERT INTO "oc_appconfig" VALUES('oauth2','types','authentication');
INSERT INTO "oc_appconfig" VALUES('oauth2','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('files_pdfviewer','installed_version','1.4.0');
INSERT INTO "oc_appconfig" VALUES('files_pdfviewer','types','');
INSERT INTO "oc_appconfig" VALUES('files_pdfviewer','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('federation','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('federation','types','authentication');
INSERT INTO "oc_appconfig" VALUES('federation','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('files_videoplayer','installed_version','1.4.0');
INSERT INTO "oc_appconfig" VALUES('files_videoplayer','types','');
INSERT INTO "oc_appconfig" VALUES('files_videoplayer','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('cloud_federation_api','installed_version','0.1.0');
INSERT INTO "oc_appconfig" VALUES('cloud_federation_api','types','filesystem');
INSERT INTO "oc_appconfig" VALUES('cloud_federation_api','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('updatenotification','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('updatenotification','types','');
INSERT INTO "oc_appconfig" VALUES('updatenotification','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('federatedfilesharing','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('federatedfilesharing','types','');
INSERT INTO "oc_appconfig" VALUES('federatedfilesharing','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('support','installed_version','1.0.0');
INSERT INTO "oc_appconfig" VALUES('support','types','');
INSERT INTO "oc_appconfig" VALUES('support','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('provisioning_api','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('provisioning_api','types','prevent_group_restriction');
INSERT INTO "oc_appconfig" VALUES('provisioning_api','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('sharebymail','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('sharebymail','types','filesystem');
INSERT INTO "oc_appconfig" VALUES('sharebymail','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('nextcloud_announcements','installed_version','1.4.0');
INSERT INTO "oc_appconfig" VALUES('nextcloud_announcements','types','logging');
INSERT INTO "oc_appconfig" VALUES('nextcloud_announcements','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('gallery','installed_version','18.2.0');
INSERT INTO "oc_appconfig" VALUES('gallery','types','');
INSERT INTO "oc_appconfig" VALUES('gallery','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('files_versions','installed_version','1.8.0');
INSERT INTO "oc_appconfig" VALUES('files_versions','types','filesystem,dav');
INSERT INTO "oc_appconfig" VALUES('files_versions','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('accessibility','installed_version','1.1.0');
INSERT INTO "oc_appconfig" VALUES('accessibility','types','');
INSERT INTO "oc_appconfig" VALUES('accessibility','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('files','installed_version','1.10.0');
INSERT INTO "oc_appconfig" VALUES('files','types','filesystem');
INSERT INTO "oc_appconfig" VALUES('files','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('workflowengine','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('workflowengine','types','filesystem');
INSERT INTO "oc_appconfig" VALUES('workflowengine','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('theming','installed_version','1.6.0');
INSERT INTO "oc_appconfig" VALUES('theming','types','logging');
INSERT INTO "oc_appconfig" VALUES('theming','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('twofactor_backupcodes','installed_version','1.4.1');
INSERT INTO "oc_appconfig" VALUES('twofactor_backupcodes','types','');
INSERT INTO "oc_appconfig" VALUES('twofactor_backupcodes','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('systemtags','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('systemtags','types','logging');
INSERT INTO "oc_appconfig" VALUES('systemtags','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('files_sharing','installed_version','1.7.0');
INSERT INTO "oc_appconfig" VALUES('core','public_files','files_sharing/public.php');
INSERT INTO "oc_appconfig" VALUES('files_sharing','types','filesystem');
INSERT INTO "oc_appconfig" VALUES('files_sharing','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('serverinfo','installed_version','1.5.0');
INSERT INTO "oc_appconfig" VALUES('serverinfo','types','');
INSERT INTO "oc_appconfig" VALUES('serverinfo','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('backgroundjob','lastjob','17');
INSERT INTO "oc_appconfig" VALUES('core','lastcron','1548321571');
INSERT INTO "oc_appconfig" VALUES('core','scss.variables','db81cddf52fdb3c8ca1e4c859e214124');
INSERT INTO "oc_appconfig" VALUES('user_saml','installed_version','2.1.0');
INSERT INTO "oc_appconfig" VALUES('user_saml','enabled','yes');
INSERT INTO "oc_appconfig" VALUES('user_saml','types','authentication');
INSERT INTO "oc_appconfig" VALUES('user_saml','type','environment-variable');
INSERT INTO "oc_appconfig" VALUES('user_saml','general-uid_mapping','MELLON_uid');
INSERT INTO "oc_appconfig" VALUES('user_saml','saml-attribute-mapping-group_mapping','MELLON_memberOf');
INSERT INTO "oc_appconfig" VALUES('nextcloud_announcements','pub_date','Sat, 10 Dec 2016 00:00:00 +0100');
INSERT INTO "oc_appconfig" VALUES('files','cronjob_scan_files','500');
CREATE TABLE oc_storages (numeric_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, id VARCHAR(64) DEFAULT NULL, available INTEGER DEFAULT 1 NOT NULL, last_checked INTEGER DEFAULT NULL);
INSERT INTO "oc_storages" VALUES(1,'home::admin',1,NULL);
INSERT INTO "oc_storages" VALUES(2,'local::/var/www/html/data/',1,NULL);
CREATE TABLE oc_mounts (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, storage_id INTEGER NOT NULL, root_id INTEGER NOT NULL, user_id VARCHAR(64) NOT NULL, mount_point VARCHAR(4000) NOT NULL, mount_id INTEGER DEFAULT NULL);
INSERT INTO "oc_mounts" VALUES(1,1,1,'admin','/admin/',NULL);
CREATE TABLE oc_mimetypes (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, mimetype VARCHAR(255) DEFAULT '' NOT NULL);
INSERT INTO "oc_mimetypes" VALUES(1,'httpd');
INSERT INTO "oc_mimetypes" VALUES(2,'httpd/unix-directory');
INSERT INTO "oc_mimetypes" VALUES(3,'image');
INSERT INTO "oc_mimetypes" VALUES(4,'image/jpeg');
INSERT INTO "oc_mimetypes" VALUES(5,'video');
INSERT INTO "oc_mimetypes" VALUES(6,'video/mp4');
INSERT INTO "oc_mimetypes" VALUES(7,'application');
INSERT INTO "oc_mimetypes" VALUES(8,'application/pdf');
INSERT INTO "oc_mimetypes" VALUES(9,'image/png');
INSERT INTO "oc_mimetypes" VALUES(10,'application/vnd.oasis.opendocument.text');
INSERT INTO "oc_mimetypes" VALUES(11,'text');
INSERT INTO "oc_mimetypes" VALUES(12,'text/plain');
INSERT INTO "oc_mimetypes" VALUES(13,'application/javascript');
INSERT INTO "oc_mimetypes" VALUES(14,'application/octet-stream');
INSERT INTO "oc_mimetypes" VALUES(15,'application/x-gzip');
INSERT INTO "oc_mimetypes" VALUES(16,'text/css');
INSERT INTO "oc_mimetypes" VALUES(17,'application/json');
INSERT INTO "oc_mimetypes" VALUES(18,'image/svg+xml');
CREATE TABLE oc_filecache (fileid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, storage BIGINT DEFAULT 0 NOT NULL, path VARCHAR(4000) DEFAULT NULL, path_hash VARCHAR(32) DEFAULT '' NOT NULL, parent BIGINT DEFAULT 0 NOT NULL, name VARCHAR(250) DEFAULT NULL, mimetype BIGINT DEFAULT 0 NOT NULL, mimepart BIGINT DEFAULT 0 NOT NULL, size BIGINT DEFAULT 0 NOT NULL, mtime INTEGER DEFAULT 0 NOT NULL, storage_mtime INTEGER DEFAULT 0 NOT NULL, encrypted INTEGER DEFAULT 0 NOT NULL, unencrypted_size BIGINT DEFAULT 0 NOT NULL, etag VARCHAR(40) DEFAULT NULL, permissions INTEGER DEFAULT 0, checksum VARCHAR(255) DEFAULT NULL);
CREATE TABLE oc_group_user (gid VARCHAR(64) DEFAULT '' NOT NULL, uid VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY(gid, uid));
CREATE TABLE oc_group_admin (gid VARCHAR(64) DEFAULT '' NOT NULL, uid VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY(gid, uid));
CREATE TABLE oc_groups (gid VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY(gid));
INSERT INTO "oc_groups" VALUES('admin');
CREATE TABLE oc_preferences (userid VARCHAR(64) DEFAULT '' NOT NULL, appid VARCHAR(32) DEFAULT '' NOT NULL, configkey VARCHAR(64) DEFAULT '' NOT NULL, configvalue CLOB DEFAULT NULL, PRIMARY KEY(userid, appid, configkey));
CREATE TABLE oc_properties (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, userid VARCHAR(64) DEFAULT '' NOT NULL, propertypath VARCHAR(255) DEFAULT '' NOT NULL, propertyname VARCHAR(255) DEFAULT '' NOT NULL, propertyvalue CLOB NOT NULL);
CREATE TABLE oc_jobs (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, class VARCHAR(255) DEFAULT '' NOT NULL, argument VARCHAR(4000) DEFAULT '' NOT NULL, last_run INTEGER DEFAULT 0, last_checked INTEGER DEFAULT 0, reserved_at INTEGER DEFAULT 0, execution_duration INTEGER DEFAULT 0 NOT NULL);
INSERT INTO "oc_jobs" VALUES(2,'OCA\DAV\BackgroundJob\CleanupDirectLinksJob','null',1548317994,1548317994,0,0);
INSERT INTO "oc_jobs" VALUES(3,'OCA\DAV\BackgroundJob\UpdateCalendarResourcesRoomsBackgroundJob','null',1548318035,1548318035,0,0);
INSERT INTO "oc_jobs" VALUES(4,'OCA\DAV\BackgroundJob\CleanupInvitationTokenJob','null',1548318054,1548318054,0,0);
INSERT INTO "oc_jobs" VALUES(5,'OCA\Files_Trashbin\BackgroundJob\ExpireTrash','null',1548318059,1548318059,0,0);
INSERT INTO "oc_jobs" VALUES(6,'OCA\Activity\BackgroundJob\EmailNotification','null',1548318206,1548318206,0,0);
INSERT INTO "oc_jobs" VALUES(7,'OCA\Activity\BackgroundJob\ExpireActivities','null',1548318891,1548318891,0,0);
INSERT INTO "oc_jobs" VALUES(8,'OCA\Federation\SyncJob','null',1548318899,1548318899,0,0);
INSERT INTO "oc_jobs" VALUES(9,'OCA\UpdateNotification\Notification\BackgroundJob','null',1548318904,1548318904,0,0);
INSERT INTO "oc_jobs" VALUES(10,'OCA\Support\BackgroundJobs\CheckSubscription','null',1548320753,1548320753,0,0);
INSERT INTO "oc_jobs" VALUES(11,'OCA\NextcloudAnnouncements\Cron\Crawler','null',1548320762,1548320762,0,0);
INSERT INTO "oc_jobs" VALUES(12,'OCA\Files_Versions\BackgroundJob\ExpireVersions','null',1548320773,1548320773,0,0);
INSERT INTO "oc_jobs" VALUES(13,'OCA\Files\BackgroundJob\ScanFiles','null',1548320775,1548320775,0,0);
INSERT INTO "oc_jobs" VALUES(14,'OCA\Files\BackgroundJob\DeleteOrphanedItems','null',1548321192,1548321192,0,0);
INSERT INTO "oc_jobs" VALUES(15,'OCA\Files\BackgroundJob\CleanupFileLocks','null',1548321280,1548321279,0,0);
INSERT INTO "oc_jobs" VALUES(16,'OCA\Files_Sharing\DeleteOrphanedSharesJob','null',1548321549,1548321549,0,0);
INSERT INTO "oc_jobs" VALUES(17,'OCA\Files_Sharing\ExpireSharesJob','null',1548321571,1548321571,0,0);
INSERT INTO "oc_jobs" VALUES(18,'OCA\Files_Sharing\BackgroundJob\FederatedSharesDiscoverJob','null',0,1548317957,0,0);
INSERT INTO "oc_jobs" VALUES(19,'OC\Authentication\Token\DefaultTokenCleanupJob','null',0,1548317957,0,0);
INSERT INTO "oc_jobs" VALUES(20,'OC\Log\Rotate','null',0,1548317957,0,0);
INSERT INTO "oc_jobs" VALUES(21,'OC\Preview\BackgroundCleanupJob','null',0,1548317957,0,0);
INSERT INTO "oc_jobs" VALUES(22,'OCA\FirstRunWizard\Notification\BackgroundJob','{"uid":"admin"}',0,1548317972,0,0);
CREATE TABLE oc_bruteforce_attempts (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "action" VARCHAR(64) DEFAULT '' NOT NULL, occurred INTEGER UNSIGNED DEFAULT 0 NOT NULL, ip VARCHAR(255) DEFAULT '' NOT NULL, subnet VARCHAR(255) DEFAULT '' NOT NULL, metadata VARCHAR(255) DEFAULT '' NOT NULL);
CREATE TABLE oc_vcategory (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, uid VARCHAR(64) DEFAULT '' NOT NULL, type VARCHAR(64) DEFAULT '' NOT NULL, category VARCHAR(255) DEFAULT '' NOT NULL);
CREATE TABLE oc_systemtag (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name VARCHAR(64) DEFAULT '' NOT NULL, visibility SMALLINT DEFAULT 1 NOT NULL, editable SMALLINT DEFAULT 1 NOT NULL);
CREATE TABLE oc_file_locks (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, lock INTEGER DEFAULT 0 NOT NULL, "key" VARCHAR(64) NOT NULL, ttl INTEGER DEFAULT -1 NOT NULL);
CREATE TABLE oc_comments_read_markers (user_id VARCHAR(64) DEFAULT '' NOT NULL, marker_datetime DATETIME DEFAULT NULL, object_type VARCHAR(64) DEFAULT '' NOT NULL, object_id VARCHAR(64) DEFAULT '' NOT NULL);
CREATE TABLE oc_credentials (user VARCHAR(64) NOT NULL, identifier VARCHAR(64) NOT NULL, credentials CLOB DEFAULT NULL, PRIMARY KEY(user, identifier));
CREATE TABLE oc_accounts (uid VARCHAR(64) DEFAULT '' NOT NULL, data CLOB DEFAULT '' NOT NULL, PRIMARY KEY(uid));
INSERT INTO "oc_accounts" VALUES('admin','{"displayname":{"value":"admin","scope":"contacts","verified":"0"},"address":{"value":"","scope":"private","verified":"0"},"website":{"value":"","scope":"private","verified":"0"},"email":{"value":null,"scope":"contacts","verified":"0"},"avatar":{"scope":"contacts"},"phone":{"value":"","scope":"private","verified":"0"},"twitter":{"value":"","scope":"private","verified":"0"}}');
CREATE TABLE oc_comments (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, children_count INTEGER UNSIGNED DEFAULT 0 NOT NULL, actor_type VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, actor_id VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, message CLOB DEFAULT NULL COLLATE BINARY, verb VARCHAR(64) DEFAULT NULL COLLATE BINARY, creation_timestamp DATETIME DEFAULT NULL, latest_child_timestamp DATETIME DEFAULT NULL, object_type VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, object_id VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, parent_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, topmost_parent_id BIGINT UNSIGNED DEFAULT 0 NOT NULL);
CREATE TABLE oc_share (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, share_type SMALLINT DEFAULT 0 NOT NULL, share_with VARCHAR(255) DEFAULT NULL COLLATE BINARY, password VARCHAR(255) DEFAULT NULL COLLATE BINARY, uid_owner VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, uid_initiator VARCHAR(64) DEFAULT NULL COLLATE BINARY, item_type VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, item_source VARCHAR(255) DEFAULT NULL COLLATE BINARY, item_target VARCHAR(255) DEFAULT NULL COLLATE BINARY, file_target VARCHAR(512) DEFAULT NULL COLLATE BINARY, permissions SMALLINT DEFAULT 0 NOT NULL, stime BIGINT DEFAULT 0 NOT NULL, accepted SMALLINT DEFAULT 0 NOT NULL, expiration DATETIME DEFAULT NULL, token VARCHAR(32) DEFAULT NULL COLLATE BINARY, mail_send SMALLINT DEFAULT 0 NOT NULL, share_name VARCHAR(64) DEFAULT NULL COLLATE BINARY, parent BIGINT DEFAULT NULL, file_source BIGINT DEFAULT NULL, password_by_talk BOOLEAN DEFAULT '0' NOT NULL, note CLOB DEFAULT NULL, hide_download SMALLINT DEFAULT 0 NOT NULL, label VARCHAR(255) DEFAULT NULL);
CREATE TABLE oc_systemtag_group (gid VARCHAR(255) NOT NULL COLLATE BINARY, systemtagid BIGINT UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(gid, systemtagid));
CREATE TABLE oc_systemtag_object_mapping (objectid VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, objecttype VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, systemtagid BIGINT UNSIGNED DEFAULT 0 NOT NULL);
CREATE TABLE oc_vcategory_to_object (categoryid BIGINT UNSIGNED DEFAULT 0 NOT NULL, objid BIGINT UNSIGNED DEFAULT 0 NOT NULL, type VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, PRIMARY KEY(categoryid, objid, type));
CREATE TABLE oc_users (uid VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, displayname VARCHAR(64) DEFAULT NULL COLLATE BINARY, password VARCHAR(255) DEFAULT '' NOT NULL COLLATE BINARY, uid_lower VARCHAR(64) DEFAULT '', PRIMARY KEY(uid));
INSERT INTO "oc_users" VALUES('admin',NULL,'2|$argon2i$v=19$m=1024,t=2,p=2$WW9qTGJNcFB2Y2ZzWVhEWg$VRAyFaH/QCIdP080tDjZVdUEByi78micsrFCDzSIk7g','admin');
CREATE TABLE oc_authtoken (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, uid VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, login_name VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, password CLOB DEFAULT NULL COLLATE BINARY, name CLOB DEFAULT '' NOT NULL COLLATE BINARY, token VARCHAR(200) DEFAULT '' NOT NULL COLLATE BINARY, type SMALLINT UNSIGNED DEFAULT 0 NOT NULL, remember SMALLINT UNSIGNED DEFAULT 0 NOT NULL, last_activity INTEGER UNSIGNED DEFAULT 0 NOT NULL, last_check INTEGER UNSIGNED DEFAULT 0 NOT NULL, scope CLOB DEFAULT NULL COLLATE BINARY, expires INTEGER UNSIGNED DEFAULT NULL, private_key CLOB DEFAULT NULL, public_key CLOB DEFAULT NULL, version SMALLINT UNSIGNED DEFAULT 1 NOT NULL, password_invalid BOOLEAN DEFAULT '0' NOT NULL);
CREATE TABLE oc_twofactor_providers (provider_id VARCHAR(32) NOT NULL, uid VARCHAR(64) NOT NULL, enabled SMALLINT NOT NULL, PRIMARY KEY(provider_id, uid));
INSERT INTO "oc_twofactor_providers" VALUES('backup_codes','admin',0);
CREATE TABLE oc_whats_new (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, version VARCHAR(64) DEFAULT '11' NOT NULL, etag VARCHAR(64) DEFAULT '' NOT NULL, last_check INTEGER UNSIGNED DEFAULT 0 NOT NULL, data CLOB DEFAULT '' NOT NULL);
CREATE TABLE oc_addressbooks (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, principaluri VARCHAR(255) DEFAULT NULL, displayname VARCHAR(255) DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, synctoken INTEGER UNSIGNED DEFAULT 1 NOT NULL);
INSERT INTO "oc_addressbooks" VALUES(1,'principals/users/admin','Contacts','contacts',NULL,1);
CREATE TABLE oc_calendars (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, principaluri VARCHAR(255) DEFAULT NULL, displayname VARCHAR(255) DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, synctoken INTEGER UNSIGNED DEFAULT 1 NOT NULL, description VARCHAR(255) DEFAULT NULL, calendarorder INTEGER UNSIGNED DEFAULT 0 NOT NULL, calendarcolor VARCHAR(255) DEFAULT NULL, timezone CLOB DEFAULT NULL, components VARCHAR(64) DEFAULT NULL, transparent SMALLINT DEFAULT 0 NOT NULL);
INSERT INTO "oc_calendars" VALUES(1,'principals/users/admin','Personal','personal',1,NULL,0,NULL,NULL,'VEVENT,VTODO',0);
CREATE TABLE oc_schedulingobjects (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, principaluri VARCHAR(255) DEFAULT NULL, calendardata BLOB DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL, lastmodified INTEGER UNSIGNED DEFAULT NULL, etag VARCHAR(32) DEFAULT NULL, size BIGINT UNSIGNED NOT NULL);
CREATE TABLE oc_cards_properties (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, addressbookid BIGINT DEFAULT 0 NOT NULL, cardid BIGINT UNSIGNED DEFAULT 0 NOT NULL, name VARCHAR(64) DEFAULT NULL COLLATE BINARY, value VARCHAR(255) DEFAULT NULL COLLATE BINARY, preferred INTEGER DEFAULT 1 NOT NULL);
CREATE TABLE oc_addressbookchanges (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, uri VARCHAR(255) DEFAULT NULL COLLATE BINARY, synctoken INTEGER UNSIGNED DEFAULT 1 NOT NULL, operation SMALLINT NOT NULL, addressbookid BIGINT NOT NULL);
CREATE TABLE oc_cards (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, carddata BLOB DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL COLLATE BINARY, lastmodified BIGINT UNSIGNED DEFAULT NULL, etag VARCHAR(32) DEFAULT NULL COLLATE BINARY, size BIGINT UNSIGNED NOT NULL, addressbookid BIGINT DEFAULT 0 NOT NULL, uid VARCHAR(255) DEFAULT NULL);
CREATE TABLE oc_dav_shares (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, principaluri VARCHAR(255) DEFAULT NULL COLLATE BINARY, type VARCHAR(255) DEFAULT NULL COLLATE BINARY, access SMALLINT DEFAULT NULL, publicuri VARCHAR(255) DEFAULT NULL COLLATE BINARY, resourceid BIGINT UNSIGNED NOT NULL);
CREATE TABLE oc_directlink (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, user_id VARCHAR(64) DEFAULT NULL, file_id BIGINT UNSIGNED NOT NULL, token VARCHAR(60) DEFAULT NULL, expiration BIGINT UNSIGNED NOT NULL);
CREATE TABLE oc_calendar_resources (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, backend_id VARCHAR(64) DEFAULT NULL, resource_id VARCHAR(64) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, displayname VARCHAR(255) DEFAULT NULL, group_restrictions VARCHAR(4000) DEFAULT NULL);
CREATE TABLE oc_calendar_rooms (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, backend_id VARCHAR(64) DEFAULT NULL, resource_id VARCHAR(64) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, displayname VARCHAR(255) DEFAULT NULL, group_restrictions VARCHAR(4000) DEFAULT NULL);
CREATE TABLE oc_calendar_invitations (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, uid VARCHAR(255) NOT NULL, recurrenceid VARCHAR(255) DEFAULT NULL, attendee VARCHAR(255) NOT NULL, organizer VARCHAR(255) NOT NULL, sequence BIGINT UNSIGNED DEFAULT NULL, token VARCHAR(60) NOT NULL, expiration BIGINT UNSIGNED NOT NULL);
CREATE TABLE oc_calendarchanges (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, uri VARCHAR(255) DEFAULT NULL COLLATE BINARY, synctoken INTEGER UNSIGNED DEFAULT 1 NOT NULL, operation SMALLINT NOT NULL, calendarid BIGINT NOT NULL, calendartype INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE oc_calendarobjects (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, calendardata BLOB DEFAULT NULL, uri VARCHAR(255) DEFAULT NULL COLLATE BINARY, lastmodified INTEGER UNSIGNED DEFAULT NULL, etag VARCHAR(32) DEFAULT NULL COLLATE BINARY, size BIGINT UNSIGNED NOT NULL, componenttype VARCHAR(8) DEFAULT NULL COLLATE BINARY, firstoccurence BIGINT UNSIGNED DEFAULT NULL, lastoccurence BIGINT UNSIGNED DEFAULT NULL, uid VARCHAR(255) DEFAULT NULL COLLATE BINARY, classification INTEGER DEFAULT 0, calendarid BIGINT UNSIGNED NOT NULL, calendartype INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE oc_calendarobjects_props (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, calendarid BIGINT DEFAULT 0 NOT NULL, objectid BIGINT UNSIGNED DEFAULT 0 NOT NULL, name VARCHAR(64) DEFAULT NULL COLLATE BINARY, parameter VARCHAR(64) DEFAULT NULL COLLATE BINARY, value VARCHAR(255) DEFAULT NULL COLLATE BINARY, calendartype INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE oc_calendarsubscriptions (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, uri VARCHAR(255) DEFAULT NULL COLLATE BINARY, principaluri VARCHAR(255) DEFAULT NULL COLLATE BINARY, displayname VARCHAR(100) DEFAULT NULL COLLATE BINARY, refreshrate VARCHAR(10) DEFAULT NULL COLLATE BINARY, calendarorder INTEGER UNSIGNED DEFAULT 0 NOT NULL, calendarcolor VARCHAR(255) DEFAULT NULL COLLATE BINARY, striptodos SMALLINT DEFAULT NULL, stripalarms SMALLINT DEFAULT NULL, stripattachments SMALLINT DEFAULT NULL, lastmodified INTEGER UNSIGNED DEFAULT NULL, synctoken INTEGER UNSIGNED DEFAULT 1 NOT NULL, source CLOB DEFAULT NULL COLLATE BINARY);
CREATE TABLE IF NOT EXISTS "oc_files_trash" ("auto_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "id" VARCHAR(250) DEFAULT '' NOT NULL, "user" VARCHAR(64) DEFAULT '' NOT NULL, "timestamp" VARCHAR(12) DEFAULT '' NOT NULL, "location" VARCHAR(512) DEFAULT '' NOT NULL, "type" VARCHAR(4) DEFAULT NULL, "mime" VARCHAR(255) DEFAULT NULL);
CREATE TABLE oc_activity (activity_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, timestamp INTEGER DEFAULT 0 NOT NULL, priority INTEGER DEFAULT 0 NOT NULL, type VARCHAR(255) DEFAULT NULL, user VARCHAR(64) DEFAULT NULL, affecteduser VARCHAR(64) NOT NULL, app VARCHAR(32) NOT NULL, subject VARCHAR(255) NOT NULL, subjectparams CLOB NOT NULL, message VARCHAR(255) DEFAULT NULL, messageparams CLOB DEFAULT NULL, file VARCHAR(4000) DEFAULT NULL, link VARCHAR(4000) DEFAULT NULL, object_type VARCHAR(255) DEFAULT NULL, object_id BIGINT DEFAULT 0 NOT NULL);
CREATE TABLE oc_activity_mq (mail_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, amq_timestamp INTEGER DEFAULT 0 NOT NULL, amq_latest_send INTEGER DEFAULT 0 NOT NULL, amq_type VARCHAR(255) NOT NULL, amq_affecteduser VARCHAR(64) NOT NULL, amq_appid VARCHAR(255) NOT NULL, amq_subject VARCHAR(255) NOT NULL, amq_subjectparams VARCHAR(4000) NOT NULL, object_type VARCHAR(255) DEFAULT NULL, object_id BIGINT DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS "oc_notifications" ("notification_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "app" VARCHAR(32) NOT NULL, "user" VARCHAR(64) NOT NULL, "timestamp" INTEGER DEFAULT 0 NOT NULL, "object_type" VARCHAR(64) NOT NULL, "object_id" VARCHAR(64) NOT NULL, "subject" VARCHAR(64) NOT NULL, "subject_parameters" CLOB DEFAULT NULL, "message" VARCHAR(64) DEFAULT NULL, "message_parameters" CLOB DEFAULT NULL, "link" VARCHAR(4000) DEFAULT NULL, "icon" VARCHAR(4000) DEFAULT NULL, "actions" CLOB DEFAULT NULL);
INSERT INTO "oc_notifications" VALUES(1,'survey_client','admin',1548317969,'dummy','23','updated','[]','','[]','','','[{"label":"enable","link":"http:\/\/localhost:8001\/ocs\/v2.php\/apps\/survey_client\/api\/v1\/monthly","type":"POST","primary":true},{"label":"disable","link":"http:\/\/localhost:8001\/ocs\/v2.php\/apps\/survey_client\/api\/v1\/monthly","type":"DELETE","primary":false}]');
CREATE TABLE IF NOT EXISTS "oc_notifications_pushtokens" ("uid" VARCHAR(64) NOT NULL, "token" INTEGER DEFAULT 0 NOT NULL, "deviceidentifier" VARCHAR(128) NOT NULL, "devicepublickey" VARCHAR(512) NOT NULL, "devicepublickeyhash" VARCHAR(128) NOT NULL, "pushtokenhash" VARCHAR(128) NOT NULL, "proxyserver" VARCHAR(256) NOT NULL, "apptype" VARCHAR(32) DEFAULT 'unknown' NOT NULL);
CREATE TABLE IF NOT EXISTS "oc_oauth2_clients" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" VARCHAR(64) NOT NULL, "redirect_uri" VARCHAR(2000) NOT NULL, "client_identifier" VARCHAR(64) NOT NULL, "secret" VARCHAR(64) NOT NULL);
CREATE TABLE IF NOT EXISTS "oc_oauth2_access_tokens" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "token_id" INTEGER NOT NULL, "client_id" INTEGER NOT NULL, "hashed_code" VARCHAR(128) NOT NULL, "encrypted_token" VARCHAR(786) NOT NULL);
CREATE TABLE IF NOT EXISTS "oc_trusted_servers" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "url" VARCHAR(512) NOT NULL, "url_hash" VARCHAR(255) DEFAULT '' NOT NULL, "token" VARCHAR(128) DEFAULT NULL, "shared_secret" VARCHAR(256) DEFAULT NULL, "status" INTEGER DEFAULT 2 NOT NULL, "sync_token" VARCHAR(512) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS "oc_federated_reshares" ("share_id" INTEGER NOT NULL, "remote_id" INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS "oc_flow_checks" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "class" VARCHAR(256) NOT NULL, "operator" VARCHAR(16) NOT NULL, "value" CLOB DEFAULT NULL, "hash" VARCHAR(32) NOT NULL);
CREATE TABLE IF NOT EXISTS "oc_flow_operations" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "class" VARCHAR(256) NOT NULL, "name" VARCHAR(256) NOT NULL, "checks" CLOB DEFAULT NULL, "operation" CLOB DEFAULT NULL);
CREATE TABLE oc_twofactor_backupcodes (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, user_id VARCHAR(64) DEFAULT '' NOT NULL COLLATE BINARY, used SMALLINT DEFAULT 0 NOT NULL, code VARCHAR(128) NOT NULL COLLATE BINARY);
CREATE TABLE IF NOT EXISTS "oc_share_external" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "parent" INTEGER DEFAULT -1, "share_type" INTEGER DEFAULT NULL, "remote" VARCHAR(512) NOT NULL, "remote_id" INTEGER DEFAULT -1 NOT NULL, "share_token" VARCHAR(64) NOT NULL, "password" VARCHAR(64) DEFAULT NULL, "name" VARCHAR(64) NOT NULL, "owner" VARCHAR(64) NOT NULL, "user" VARCHAR(64) NOT NULL, "mountpoint" VARCHAR(4000) NOT NULL, "mountpoint_hash" VARCHAR(32) NOT NULL, "accepted" INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS "oc_user_saml_users" ("uid" VARCHAR(64) DEFAULT '' NOT NULL, "displayname" VARCHAR(255) DEFAULT '' NOT NULL, "home" VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("uid"));
CREATE TABLE IF NOT EXISTS "oc_user_saml_auth_token" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "uid" VARCHAR(64) DEFAULT '' NOT NULL, "name" CLOB DEFAULT '' NOT NULL, "token" VARCHAR(200) DEFAULT '' NOT NULL);
CREATE INDEX appconfig_config_key_index ON oc_appconfig (configkey);
CREATE INDEX appconfig_appid_key ON oc_appconfig (appid);
CREATE UNIQUE INDEX storages_id_index ON oc_storages (id);
CREATE INDEX mounts_user_index ON oc_mounts (user_id);
CREATE INDEX mounts_storage_index ON oc_mounts (storage_id);
CREATE INDEX mounts_root_index ON oc_mounts (root_id);
CREATE INDEX mounts_mount_id_index ON oc_mounts (mount_id);
CREATE UNIQUE INDEX mounts_user_root_index ON oc_mounts (user_id, root_id);
CREATE UNIQUE INDEX mimetype_id_index ON oc_mimetypes (mimetype);
CREATE UNIQUE INDEX fs_storage_path_hash ON oc_filecache (storage, path_hash);
CREATE INDEX fs_parent_name_hash ON oc_filecache (parent, name);
CREATE INDEX fs_storage_mimetype ON oc_filecache (storage, mimetype);
CREATE INDEX fs_storage_mimepart ON oc_filecache (storage, mimepart);
CREATE INDEX fs_storage_size ON oc_filecache (storage, size, fileid);
CREATE INDEX fs_mtime ON oc_filecache (mtime);
CREATE INDEX gu_uid_index ON oc_group_user (uid);
CREATE INDEX group_admin_uid ON oc_group_admin (uid);
CREATE INDEX property_index ON oc_properties (userid);
CREATE INDEX job_class_index ON oc_jobs (class);
CREATE INDEX bruteforce_attempts_ip ON oc_bruteforce_attempts (ip);
CREATE INDEX bruteforce_attempts_subnet ON oc_bruteforce_attempts (subnet);
CREATE INDEX uid_index ON oc_vcategory (uid);
CREATE INDEX type_index ON oc_vcategory (type);
CREATE INDEX category_index ON oc_vcategory (category);
CREATE UNIQUE INDEX tag_ident ON oc_systemtag (name, visibility, editable);
CREATE UNIQUE INDEX lock_key_index ON oc_file_locks ("key");
CREATE INDEX lock_ttl_index ON oc_file_locks (ttl);
CREATE INDEX comments_marker_object_index ON oc_comments_read_markers (object_type, object_id);
CREATE UNIQUE INDEX comments_marker_index ON oc_comments_read_markers (user_id, object_type, object_id);
CREATE INDEX credentials_user ON oc_credentials (user);
CREATE INDEX comments_actor_index ON oc_comments (actor_type, actor_id);
CREATE INDEX comments_object_index ON oc_comments (object_type, object_id, creation_timestamp);
CREATE INDEX comments_topmost_parent_id_idx ON oc_comments (topmost_parent_id);
CREATE INDEX comments_parent_id_index ON oc_comments (parent_id);
CREATE INDEX initiator_index ON oc_share (uid_initiator);
CREATE INDEX owner_index ON oc_share (uid_owner);
CREATE INDEX parent_index ON oc_share (parent);
CREATE INDEX share_with_index ON oc_share (share_with);
CREATE INDEX token_index ON oc_share (token);
CREATE INDEX file_source_index ON oc_share (file_source);
CREATE INDEX item_share_type_index ON oc_share (item_type, share_type);
CREATE UNIQUE INDEX mapping ON oc_systemtag_object_mapping (objecttype, objectid, systemtagid);
CREATE INDEX vcategory_objectd_index ON oc_vcategory_to_object (objid, type);
CREATE INDEX user_uid_lower ON oc_users (uid_lower);
CREATE INDEX authtoken_last_activity_index ON oc_authtoken (last_activity);
CREATE UNIQUE INDEX authtoken_token_index ON oc_authtoken (token);
CREATE INDEX authtoken_uid_index ON oc_authtoken (uid);
CREATE INDEX authtoken_version_index ON oc_authtoken (version);
CREATE UNIQUE INDEX UNIQ_333A1DC2BF1CD3C3 ON oc_whats_new (version);
CREATE INDEX version_etag_idx ON oc_whats_new (version, etag);
CREATE UNIQUE INDEX addressbook_index ON oc_addressbooks (principaluri, uri);
CREATE UNIQUE INDEX calendars_index ON oc_calendars (principaluri, uri);
CREATE INDEX card_value_index ON oc_cards_properties (value);
CREATE INDEX card_name_index ON oc_cards_properties (name);
CREATE INDEX card_contactid_index ON oc_cards_properties (cardid);
CREATE INDEX IDX_811F5CFA8B26C2E9 ON oc_cards_properties (addressbookid);
CREATE INDEX addressbookid_synctoken ON oc_addressbookchanges (addressbookid, synctoken);
CREATE INDEX IDX_E98F2EC48B26C2E9 ON oc_cards (addressbookid);
CREATE UNIQUE INDEX dav_shares_index ON oc_dav_shares (principaluri, resourceid, type, publicuri);
CREATE INDEX directlink_token_idx ON oc_directlink (token);
CREATE INDEX directlink_expiration_idx ON oc_directlink (expiration);
CREATE INDEX calendar_resources_bkdrsc ON oc_calendar_resources (backend_id, resource_id);
CREATE INDEX calendar_resources_email ON oc_calendar_resources (email);
CREATE INDEX calendar_resources_name ON oc_calendar_resources (displayname);
CREATE INDEX calendar_rooms_bkdrsc ON oc_calendar_rooms (backend_id, resource_id);
CREATE INDEX calendar_rooms_email ON oc_calendar_rooms (email);
CREATE INDEX calendar_rooms_name ON oc_calendar_rooms (displayname);
CREATE INDEX calendar_invitation_tokens ON oc_calendar_invitations (token);
CREATE INDEX calid_type_synctoken ON oc_calendarchanges (calendarid, calendartype, synctoken);
CREATE UNIQUE INDEX calobjects_index ON oc_calendarobjects (calendarid, calendartype, uri);
CREATE INDEX calendarobject_value_index ON oc_calendarobjects_props (value, calendartype);
CREATE INDEX calendarobject_name_index ON oc_calendarobjects_props (name, calendartype);
CREATE INDEX calendarobject_index ON oc_calendarobjects_props (objectid, calendartype);
CREATE UNIQUE INDEX calsub_index ON oc_calendarsubscriptions (principaluri, uri);
CREATE INDEX id_index ON "oc_files_trash" ("id");
CREATE INDEX timestamp_index ON "oc_files_trash" ("timestamp");
CREATE INDEX user_index ON "oc_files_trash" ("user");
CREATE INDEX activity_time ON oc_activity (timestamp);
CREATE INDEX activity_user_time ON oc_activity (affecteduser, timestamp);
CREATE INDEX activity_filter_by ON oc_activity (affecteduser, user, timestamp);
CREATE INDEX activity_filter ON oc_activity (affecteduser, type, app, timestamp);
CREATE INDEX activity_object ON oc_activity (object_type, object_id);
CREATE INDEX amp_user ON oc_activity_mq (amq_affecteduser);
CREATE INDEX amp_latest_send_time ON oc_activity_mq (amq_latest_send);
CREATE INDEX amp_timestamp_time ON oc_activity_mq (amq_timestamp);
CREATE INDEX oc_notifications_app ON "oc_notifications" ("app");
CREATE INDEX oc_notifications_user ON "oc_notifications" ("user");
CREATE INDEX oc_notifications_timestamp ON "oc_notifications" ("timestamp");
CREATE INDEX oc_notifications_object ON "oc_notifications" ("object_type", "object_id");
CREATE UNIQUE INDEX oc_notifpushtoken ON "oc_notifications_pushtokens" ("uid", "token");
CREATE INDEX oauth2_client_id_idx ON "oc_oauth2_clients" ("client_identifier");
CREATE UNIQUE INDEX oauth2_access_hash_idx ON "oc_oauth2_access_tokens" ("hashed_code");
CREATE INDEX oauth2_access_client_id_idx ON "oc_oauth2_access_tokens" ("client_id");
CREATE UNIQUE INDEX url_hash ON "oc_trusted_servers" ("url_hash");
CREATE UNIQUE INDEX share_id_index ON "oc_federated_reshares" ("share_id");
CREATE UNIQUE INDEX flow_unique_hash ON "oc_flow_checks" ("hash");
CREATE INDEX twofactor_backupcodes_uid ON oc_twofactor_backupcodes (user_id);
CREATE INDEX sh_external_user ON "oc_share_external" ("user");
CREATE UNIQUE INDEX sh_external_mp ON "oc_share_external" ("user", "mountpoint_hash");
COMMIT;
