---
- name: Ensure that packages are installed
  apt:
    state: present
    name:
      - libldap2-dev
      - libsasl2-dev
    install_recommends: no

#TODO: draai plsc als aparte gebruiker, niet als root.
- name: Copy plsc service files
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
    - "plsc.service"
    - "plsc.timer"
  notify:
    - "enable plsc job"

- name: Make sure clients sync directory exists
  file:
    path: "{{ plsc_dir }}"
    state: directory
    mode: 0755

- name: fetch plsc from {{ plsc_repo_url }}, version {{ plsc_version }}
  git:
    repo: "{{ plsc_repo_url }}"
    dest: "{{ plsc_dir }}"
    version: "{{ plsc_version }}"
    accept_hostkey: "yes"
    force: "yes"

- name: "Create plsc.yml source if it doesn't exist"
  template:
    src: "plsc.yml.j2"
    dest: "{{ plsc_dir }}/plsc.yml"
    mode: "0640"
  no_log: "{{sram_ansible_nolog}}"


- name: Create python3 virtualenv
  import_role:
    name: "python-venv"
  vars:
    python_venv_dir: "{{ plsc_venv_dir }}"
    python_venv_requirements: "{{ plsc_dir }}/requirements.txt"
