---
- name: "install required packages"
  apt:
    name:
      - "mariadb-server"
      - "php-fpm"
#      - "openssl"
    state: "present"

# for some weird reason, mariadb depends on rsync....
- name: "disable rsync"
  systemd:
    name: "rsync.service"
    masked: true

- name: "install required python packages"
  apt:
    name:
      - "python3-pip"
      - "python3-setuptools"
      - "python3-wheel"
      - "python3-pymysql"
    install_recommends: false
    state: "present"

- name: "create groups for zabbix"
  group:
    name: "{{item}}"
    state: present
  with_items:
    - "{{zabbix_php_fpm_conf_group}}"
    - "{{zabbix_web_conf_web_group}}"

- name: "create users for zabbix"
  user:
    name: "{{item}}"
    state: "present"
    shell: "/usr/sbin/nologin"
    system: true
  with_items:
    - "{{zabbix_php_fpm_conf_user}}"
    - "{{zabbix_web_conf_web_user}}"

- include_role:
    name: "letsencrypt"
    public: true
  vars:
    letsencrypt_enabled: true
    letsencrypt_staging: false
    letsencrypt_hosts: ['{{ zabbix_url }}']
    letsencrypt_server: "{{ bhr14_acme_server_url }}"
    letsencrypt_eab: true
    letsencrypt_eab_keyid: "{{ bhr14_acme_eab_keyid }}"
    letsencrypt_eab_hmac: "{{ bhr14_acme_hmac_key }}"
    letsencrypt_deploy_hooks:
      - "/usr/bin/systemctl reload nginx"

- name: Install Zabbix Server
  include_role:
    name: "community.zabbix.zabbix_server"

- name: Install nginx
  include_role:
    name: "nginx"

- name: Install Zabbix Web interface
  include_role:
    name: "community.zabbix.zabbix_web"
  vars:
    zabbix_web_tls_key: "/etc/letsencrypt/live/{{zabbix_url}}/privkey.pem"
    zabbix_web_tls_crt: "/etc/letsencrypt/live/{{zabbix_url}}/fullchain.pem"

- name: Allow Zabbix fpm user to access config file
  ansible.posix.acl:
    path: "/etc/zabbix/web/zabbix.conf.php"
    etype: "user"
    entity: "{{zabbix_php_fpm_conf_user}}"
    permissions: "r"
    state: "present"

- name: "increase zabbix cache size"
  lineinfile:
    path: "/etc/zabbix/zabbix_server.conf.d/99-zabbix-sram.conf"
    create: true
    line: "CacheSize=64M"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "flush handlers"
  meta: "flush_handlers"

- name: "setup zabbix"
  include_tasks: "setup.yml"

- name: Install zabbix backup script
  template:
    src: "backup.j2"
    dest: "/opt/backups/run.d/sram-zabbix-server.sh"
    mode: "0700"

## setup zabbix SSO
#- name: set paths to SAML keys
#  ansible.builtin.blockinfile:
#    path: "/etc/zabbix/web/zabbix.conf.php"
#    block: |
#      $SSO['SP_KEY']   = '/etc/zabbix/cert/sp.key';
#      $SSO['SP_CERT']  = '/etc/zabbix/cert/sp.crt';
#      $SSO['IDP_CERT'] = '/etc/zabbix/cert/surfconext.crt';
#    insertbefore: '^\?>'
#    marker: "// {mark} ANSIBLE MANAGED BLOCK"
