---
- name: "install required packages"
  apt:
    name:
      - "mariadb-server"
      - "php-fpm"
#      - "openssl"
    state: "present"

# for some weird reason, mariadb depends on rsync....
- name: "disable rsync"
  systemd:
    name: "rsync.service"
    masked: true

- name: "install required python packages"
  apt:
    name:
      - "python3-pip"
      - "python3-setuptools"
      - "python3-wheel"
      - "python3-pymysql"
    install_recommends: false
    state: "present"

- name: "create groups for zabbix"
  group:
    name: "{{item}}"
    state: present
  with_items:
    - "{{zabbix_php_fpm_conf_group}}"
    - "{{zabbix_web_conf_web_group}}"

- name: "create users for zabbix"
  user:
    name: "{{item}}"
    state: "present"
    shell: "/usr/sbin/nologin"
    system: true
  with_items:
    - "{{zabbix_php_fpm_conf_user}}"
    - "{{zabbix_web_conf_web_user}}"

- set_fact:
    fast: true

- name: "Fetch ACME cert for Zabbix"
  include_role:
    name: "acme"
  vars:
    acme_admin_email: "{{ admin_email }}"
    acme_certificate_list: ['{{ zabbix_url }}']
    acme_target_dir: "/etc/ssl/zabbix"
    acme_reload_command: "systemctl reload nginx"
  when: not fast

- name: Install Zabbix Server
  include_role:
    name: "community.zabbix.zabbix_server"
  when: not fast

- name: Install nginx
  include_role:
    name: "nginx"
  when: not fast

- name: Install Zabbix Web interface
  include_role:
    name: "community.zabbix.zabbix_web"
  vars:
    zabbix_web_tls_key: "/etc/ssl/zabbix/{{zabbix_url}}.key"
    zabbix_web_tls_crt: "/etc/ssl/zabbix/{{zabbix_url}}.fullchain.crt"
  when: not fast

- name: Allow Zabbix fpm user to access config file
  ansible.posix.acl:
    path: "/etc/zabbix/web/zabbix.conf.php"
    etype: "user"
    entity: "{{zabbix_php_fpm_conf_user}}"
    permissions: "r"
    state: "present"

- name: "increase zabbix cache size"
  lineinfile:
    path: "/etc/zabbix/zabbix_server.conf.d/99-zabbix-sram.conf"
    create: true
    line: "CacheSize=64M"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "flush handlers"
  meta: "flush_handlers"

- name: "setup zabbix"
  include_tasks: "setup.yml"

- name: Install zabbix backup script
  template:
    src: "backup.j2"
    dest: "/opt/backups/run.d/sram-zabbix-server.sh"
    mode: "0700"
