---
- name: Install apache
  apt:
    state: present
    name:
      - apache2
      - libapache2-mod-auth-openidc

- name: Enable apache modules
  apache2_module:
    state: present
    name: "{{ item }}"
    ignore_configcheck: true
  with_items:
    - rewrite
    - proxy_http
    - headers
  notify: "restart apache"

- name: Remove default apache config
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: "absent"
  notify: "restart apache"

- name: copy apache proxy config
  template:
    src: apache.conf.j2
    dest: /etc/apache2/sites-enabled/10-demo1.conf
    mode: 0644
  notify: "restart apache"
