---

sbs_openidc_timeout: 86400

sbs_build_url: "https://github.com/SURFscz/SBS/releases/download/{{sbs_version}}/sbs.tar.xz"
sbs_version: "branch+main"

sbs_work_dir: "{{ sram_conf_dir }}/sbs"
sbs_git_dir: "{{ sbs_work_dir }}/sbs"
sbs_env_dir: "{{ sbs_work_dir }}/sbs-env"
sbs_conf_dir: "{{ sbs_work_dir }}/config"
sbs_log_dir: "{{ sbs_work_dir }}/log"
sbs_cert_dir: "{{ sbs_work_dir }}/cert"
sbs_apache_conf: "{{ sbs_work_dir }}/sbs.conf"
sbs_nginx_conf: "{{ sbs_work_dir }}/nginx.conf"


sbs_db_host: "localhost"
sbs_db_cert_path: "{{sbs_cert_dir}}/db_ca.crt"
sbs_db_name: "sbs"
sbs_db_admin_user: "root"
sbs_db_admin_password: "changethispassword"
sbs_db_user_column_case_sensitive: false

sbs_db_user: "sbs"
sbs_dbbackup_user: "sbs_backupper"
sbs_migration_user: "sbs_migrater"

sbs_db_connection: "\
  mysql+mysqldb://%s:%s@{{ sbs_db_host }}/{{ sbs_db_name }}\
  ?ssl=true&ssl_ca=/opt/sbs/cert/db_ca.crt&charset=utf8mb4"
sbs_db_connection_sbs: "{{ sbs_db_connection | format(sbs_db_user, sbs_db_password) }}"
sbs_db_connection_migration: "\
  {{ sbs_db_connection | format(sbs_migration_user, sbs_migration_password) }}"

sbs_redis_host: "sbs-redis"
sbs_redis_port: 6379
sbs_redis_ssl: false
sbs_redis_user: default

sbs_mail_host: "{{ mail.relay_to }}"
sbs_mail_port: "{{ mail.relay_port }}"

sbs_user: "sbs"
sbs_group: "sbs"

sbs_session_lifetime: 1440
sbs_secret_key_suffix: ""

sbs_oidc_crypto_password: "CHANGEME"
sbs_uid_attribute: "sub"

sbs_disclaimer_color: "#a29c13"
sbs_disclaimer_label: wsgi

sbs_urn_namespace: "urn:example:sbs"
sbs_eppn_scope: "sbs.example.edu"
sbs_restricted_co_default_org: "example.org"

sbs_mail_sender_name: "SURF"
sbs_mail_sender_email: "no-reply@localhost"
sbs_exceptions_mail: "root@localhost"

sbs_support_email: "sram-support@localhost"
sbs_admin_email: "sram-beheer@localhost"
sbs_ticket_email: "sram-support@surf.nl"
sbs_eduteams_email: "eduteams@localhost"

sbs_wiki_link: "https://www.example.org/wiki"

sbs_backend_port: 8080
sbs_num_workers: 2

sbs_cron_hour_of_day: 4
sbs_seed_allowed: True
sbs_api_keys_enabled: True
sbs_feedback_enabled: True
sbs_audit_trail_notifications_enabled: True
sbs_send_exceptions: False
sbs_send_js_exceptions: False
sbs_second_factor_authentication_required: True
sbs_totp_token_name: "SRAM-example"
sbs_notifications_enabled: True
sbs_invitation_reminders_enabled: True
sbs_invitation_expirations_enabled: True
sbs_open_requests_enabled: True
sbs_scim_sweep: False
sbs_impersonation_allowed: True
sbs_admin_platform_backdoor_totp: True
sbs_past_dates_allowed: True
sbs_mock_scim_enabled: True
sbs_log_to_stdout: True


sbs_delete_orphaned: True
sbs_suspension_inactive_days: 365
sbs_suspension_reminder_days: 14
sbs_suspension_notify_admin: False

sbs_oidc_config_url: "http://localhost/.well-known/openid-configuration"
sbs_oidc_authz_endpoint: "http://localhost/OIDC/authorization"
sbs_oidc_token_endpoint: "http://localhost/OIDC/token"
sbs_oidc_userinfo_endpoint: "http://localhost/OIDC/userinfo"
sbs_oidc_jwks_endpoint: "http://localhost/OIDC/jwks.json"
sbs_oidc_redirect_uri: "https://sbs.scz-vm.net/api/users/resume-session"
sbs_mfa_idp_allowed: false
sbs_eduteams_continue_endpoint: "https://localhost/continue"
sbs_eb_continue_endpoint: "https://engine.(.*)surfconext.nl(.*)"
sbs_oidc_jwt_audience: "https://localhost"
sbs_continue_eduteams_redirect_uri: "https://localhost/continue"
sbs_oidc_verify_peer: False

sbs_manage_base_enabled: False
sbs_manage_base_url: "https://manage.test2.surfconext.nl"
sbs_manage_verify_peer: False

sbs_idp_metadata_url: "https://metadata.surfconext.nl/signed/2023/edugain-downstream-idp.xml "
sbs_backup_dir: "{{backup_base}}/sbs"

sbs_swagger_enabled: true

sbs_ssid_identity_providers: []
sbs_surf_secure_id:
  environment: "unknown.example.org"
  sp_entity_id: "https://sbs.{{base_domain}}"
  acs_url: "https://{{base_domain}}/api/users/acs"
  sa_gw_environment: "sa-gw.unknown.example.org"
  sa_idp_certificate: |
    -----BEGIN CERTIFICATE-----
    12345
    -----END CERTIFICATE-----
  priv: |
    -----BEGIN RSA PRIVATE KEY-----
    abcde
    -----END RSA PRIVATE KEY-----
  pub: |
    -----BEGIN CERTIFICATE-----
    12345
    -----END CERTIFICATE-----

sbs_ssid_authncontext: "\
  http://{{ sbs_surf_secure_id.environment }}/assurance/sfo-level2"
sbs_ssid_entityid: "\
  https://{{ sbs_surf_secure_id.sa_gw_environment }}/second-factor-only/metadata"
sbs_ssid_sso_endpoint: "\
  https://{{ sbs_surf_secure_id.sa_gw_environment }}/second-factor-only/single-sign-on"

sbs_mfa_sso_minutes: 10
sbs_mfa_fallback_enabled: true

sbs_ldap_url: "ldap://ldap.example.com/dc=example,dc=com"
sbs_ldap_bind_account: "cn=admin,dc=entity_id,dc=services,dc=sram-tst,dc=surf,dc=nl"

sbs_csp_style_hashes:
  - 'sha256-0+ANsgYUJdh56RK8gGvTF2vnriYqvFHfWqtA8xXa+bA='
  - 'sha256-3SnfHQolDHbZMbDAPmhrZf1keHiXfj/KJyh2phhFAAY='
  - 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='
  - 'sha256-Ng6y+QCkPChG4Q49SIfXB5ToIDcDhITtQNFkDBPpCTw='
  - 'sha256-orBPipbqpMvkNi+Z+m6qEn0XS6ymmAQE6+FwCNs1FbQ='
  - 'sha256-vFt3L2qLqpJmRpcXGbYr2UVSmgSp9VCUzz2lnqWIATw='
  - 'sha256-SU3XCwbQ/8qgzoGOWCYdkwIr3xRrl5rsvdFcpw8NSiE='  # on /new-service-request
  - 'sha256-WTC9gHKjIpzl5ub1eg/YrRy/k+jlzeyRojah9dxAApc='  # on /new-service-request

sbs_engine_block_api_token: secret
