---
metadata_web_dir: "{{metadata_documentroot}}"

metadata_idps_source: "https://metadata.surfconext.nl/idps-metadata.xml"
metadata_idps_xrd: "{{pyff_env_dir}}/certs/surfconext.xrd"
metadata_idps_feed: "{{ pyff_env_dir }}/idps_feed.fd"
metadata_idps_file: "idps.xml"
metadata_idps_target: "{{pyff_metadata_dir}}/{{ metadata_idps_file }}"
metadata_source_dir: "/opt/metadata-src"
metadata_idps_files: {}

metadata_idps_cert: |
    -----BEGIN CERTIFICATE-----
    MIIEKjCCAhICEG12w6QqayYAWntxDN59dU0wDQYJKoZIhvcNAQELBQAwPDELMAkG
    A1UEBhMCTkwxEDAOBgNVBAoMB1NVUkZuZXQxGzAZBgNVBAMMElNVUkZjb25leHQg
    Um9vdCBDQTAeFw0xOTAxMTQxNjM5MDVaFw0yNDAxMTgxNjM5MDVaMGsxCzAJBgNV
    BAYTAk5MMRAwDgYDVQQIDAdVdHJlY2h0MRAwDgYDVQQKDAdTVVJGbmV0MRMwEQYD
    VQQLDApTVVJGY29uZXh0MSMwIQYDVQQDDBpTVVJGY29uZXh0IG1ldGFkYXRhIHNp
    Z25lcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMckFyqXzW7dbMt4
    wDdSLaAjFAbNziUgQaivu4dl9Uf/cZ4f36a9DfQBUSraNoIR76ruwK3TPfFalemp
    xmWTsoVSQpb3AOsWbU+i0YKS1cmcqMUC1fef2j1IbuK4B4nEu9S5saGNVGNvUJ+Y
    jDUpC5vyyp7boW9E1md2jIBI6Mw+ZhlmkPucqaphxurWnm0KbxTZrYLOBZ1IXj6r
    yrRoFwwtjEH+CW8cRn8OATK0q4yb0BVr2gY2tp/lTpASHZ3WVWBK0prwK0KkusY6
    ck+/vvlk46IdEr803NB0Dm3ECh3i65mfCaWzVTtd/md874paK+65f1JeVyd5I5al
    M2KEpvkCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAjvJXXkxOqh3K0k2NdDG5EOTy
    bA+koRbAqhdY/qJoSnqTzwBxJc6aPs+L4q2PIoLo0gNJj1Nm1taLusaaK+CBx3ar
    1kxEika5FM0dqFjD3i7Y5U0FMeDB5cReo8TNdo31VGoY7CbRjtqHLRTuKzNmIfEm
    ahLnHIBtarE82b7Mpg0aLxjrRR+t8wSCriy+e9AEPzC5bWxtPJA+OhU8U9hMuOs5
    SzKmHwYue4WY3q1rRaDpK3fqgXRDRfznNn9/RDDbBos7CRMSAPEmAO28qLKBW/1z
    a2TKQLddZ3uoCurFNbToSTueKYVEnveQNO2P5X6uy4rcYkjeSiwbmHo7jYuHAxx4
    uGzHMpoqoGNx+2iYjtUo3dJUXzcZai3X+RuuMKXXvqGzrxJsoKayNVAE1dWoUHJl
    RouPhDLTdZq/pblORhFS8r10rKhSScgrNuN9LTTV7EPFeVr8trocNwl8IruH+eNL
    6/7b5Y7fb7rvpxeHjWrTz8a9BXAIAv+bgyrg4OHGRcNIQb0XF438HD9r8Zb92B6Z
    VCR3aVS5496+1td+8aN/Blzo59LhKPiHyGZCPHFV/oBqG7nxp603kcWmJOcG+AgB
    9bFiAimF5LLk/LnMfplK9w0vvxWVcdQkDgVPYvEGNtttj0QC7/jM4ZeihGb6Oyzy
    DZA6aeg73/ygOATQ13A=
    -----END CERTIFICATE-----
metadata_idps_filters:
  - "https://idp.surfnet.nl"
  - "https://sso.surfsara.nl/saml/saml2/idp/metadata.php"

metadata_proxy_frontend: "https://satosa.local/frontend.xml"
metadata_proxy_frontend_feed: "{{ pyff_env_dir }}/frontend_feed.fd"
metadata_proxy_frontend_entityid: "https://satosa.local/proxy"
metadata_proxy_frontend_file: "proxy_idp.xml"
metadata_proxy_frontend_target: "{{pyff_metadata_dir}}/{{ metadata_proxy_frontend_file }}"

metadata_proxy_backend: "https://satosa.local/metadata/backend.xml"
metadata_proxy_backend_feed: "{{ pyff_env_dir }}/backend_feed.fd"
metadata_proxy_backend_entityid: "https://satosa.local/metadata/backend.xml"
metadata_proxy_backend_file: "proxy_sp.xml"
metadata_proxy_backend_target: "{{pyff_metadata_dir}}/{{ metadata_proxy_backend_file }}"
