# creates local users on the machines
# in the future, we'll probably want a central ldap or so to manage the users
---
- name: set account defaults (1)
  lineinfile:
    dest: "/etc/adduser.conf"
    line: "{{item.line}}"
    regexp: "{{item.regexp}}"
    state: present
  with_items:
    - { line: "FIRST_UID=10000", regexp: "^FIRST_UID\\s*=" }
    - { line: "FIRST_GID=10000", regexp: "^FIRST_GID\\s*=" }

- name: set account defaults (2)
  lineinfile:
    dest: "/etc/login.defs"
    line: "{{item.line}}"
    regexp: "{{item.regexp}}"
    state: present
  with_items:
    - { line: "UID_MIN 10000", regexp: "^UID_MIN\\s* " }
    - { line: "GID_MIN 10000", regexp: "^GID_MIN\\s* " }

- name: set root password
  user:
    name: root
    update_password: always
    password: "{{root.pw_hash}}"

- name: create groups
  group:
    name: "{{item}}"
    state: present
  loop: >
    {{ (users|map(attribute='groups') + role_to_groups.values()|list) | flatten | unique }}

- name: remove users
  user:
    name: "{{item}}"
    state: absent
  with_items: "{{removed_users}}"

# create a user with the following groups:
# - the groups specified in the group files in the users variable
# - for each role in the roles field, the groups specified in the role_to_groups variable
- name: create users
  user:
    name: "{{item.uid}}"
    state: present
    group: "{{item.groups[0]}}"
    groups: "{{ (item.groups + item.roles | map('extract', role_to_groups)) | flatten | unique }}"
    password: "{{item.pw_hash}}"
    shell: "/bin/bash"
    comment: "{{item.name}}"
    update_password: always
  with_items: "{{users}}"

- name: copy ssh keys
  authorized_key:
    user: "{{item.uid}}"
    key: "{{ item.get('sshkey_'+inventory_hostname_short, item.sshkey) }}"
    state: present
    exclusive: true
    manage_dir: true
  with_items: "{{users}}"

- name: remove default users
  user:
    name: "{{item}}"
    state: absent
    remove: yes
  with_items:
    - surf
    - debian
