#
# Docker image ssh sandbox
#

FROM debian:stretch

RUN \
	apt-get update; \
	apt-get install -y openssh-server; \
	mkdir /var/run/sshd

RUN echo 'root:screencast' | chpasswd

RUN \
	sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config; \
	sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd


EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
