---
- name: "create group"
  group:
    name: "{{sram_tools_group}}"
    state: "present"

- name: "create directories"
  file:
    path: "{{item}}"
    state: "directory"
    mode: "0775"
    owner: "root"
    group: "{{sram_tools_group}}"
    recurse: true
  with_items:
    - "{{sram_tools_basedir}}"
    - "{{sram_tools_basedir}}/bin"
    - "{{sram_tools_wwwroot}}"

- include_tasks:
    file: "www.yml"

- include_tasks:
    file: "rapportage.yml"
