---
- include_role:
    name: "letsencrypt"
  vars:
    letsencrypt_hosts: ["{{ tools_hostname }}"]
    letsencrypt_server: "{{ bhr13_acme_server_url }}"
    letsencrypt_eab: true
    letsencrypt_eab_keyid: "{{ bhr13_acme_eab_keyid }}"
    letsencrypt_eab_hmac: "{{ bhr13_acme_hmac_key }}"

- include_role:
    name: "nginx"

- name: Install index page
  template:
    src: "index.html.j2"
    dest: "{{ sram_tools_wwwroot }}/index.html"

- name: Install links to contacts csv files
  file:
    src: "{{ contacts_dir }}/output/contacts_{{ item }}.csv"
    dest: "{{ sram_tools_wwwroot }}/contacts_{{ item }}.csv"
    state: "link"
  loop: "{{ tools_contacts_environments.keys() }}"

- name: Install links to contacts xlsx files
  file:
    src: "{{ contacts_dir }}/output/contacts_{{ item }}.xlsx"
    dest: "{{ sram_tools_wwwroot }}/contacts_{{ item }}.xlsx"
    state: "link"
  loop: "{{ tools_contacts_environments.keys() }}"

- name: Install nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/sites-enabled/01-sram-tools.conf"
  notify: "restart nginx"
