---
- include_role:
    name: "letsencrypt"
  vars:
    letsencrypt_hosts: "{{ loadbalancer | map(attribute='hostname') | list }}"

- name: Restart haproxy when cert is updated
  copy:
    content: |
      #!/bin/sh
      /usr/bin/systemctl restart haproxy
      exit 0
    path: "{{certbot_renewal_hooks}}/haproxy"
    mode: "0755"
