---
- name: set up mail relay
  include_tasks: "mailrelay.yml"
  when: "mail_relay == true"

- name: set up mail
  include_tasks: "mailleaf.yml"
  when: "mail_relay == false"

- name: clean up after exim
  apt:
    name:
      - "exim4"
      - "exim4-base"
      - "exim4-config"
      - "exim4-daemon-light"
    state: "absent"
    purge: true

