---
- name: Make sure clients sync directory exists
  file:
    path: "{{ aclsync_dir }}"
    state: directory
    mode: 0755

- name: Install plsc
  git:
    repo: "{{ plsc_repo_url }}"
    dest: "{{ aclsync_dir }}/plsc"
    version: "{{ plsc_repo_version }}"

- name: create group for aclsync config file
  group:
    name: "{{aclsync_group}}"
    state: "present"
    system: True

- name: Create config file
  template:
    src: "aclsync.yml.j2"
    dest: "{{ aclsync_dir }}/aclsync.yml"
    group: "{{aclsync_group}}"
    mode: "0640"
  no_log: "{{sram_ansible_nolog}}"

- name: Create python3 virtualenv
  import_role:
    name: "python-venv"
  vars:
    python_venv_dir: "{{ aclsync_dir }}/venv"
    python_venv_requirements: "{{ aclsync_dir }}/plsc/requirements-haproxy.txt"

- name: Copy aclsync service files
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
    - "sram_aclsync.service"
    - "sram_aclsync.timer"
  notify:
    - "enable sram_aclsync job"
