#!/bin/bash

set -e

export LC_CTYPE=C
export LC_COLLATE=C

CHARS_ALLOWED="A-Za-z0-9~!@#\$%^&*()_=+[]{}\\|;:<>,./?-"
CHARS_ALLOWED="-A-Za-z0-9_=+/%#*&"

if [ $# = 1 -a $(( $1 + 0 )) -gt 0 ]
then
    LEN=$1
else
    LEN=32
fi

ENCRYPT=0
if [ "$1" = '-e' ]
then
    ENCRYPT=1
fi

# make sure the password starts with a safe character
pw=$( openssl rand 256 | tr -cd '0-9A-Za-z' | cut -c1 )
while [ ${#pw} -lt $LEN ]
do
    pw=$pw$( openssl rand 256 | tr -cd -- "$CHARS_ALLOWED" )
    pw=${pw:0:$LEN}
done


if [ $ENCRYPT -eq 1 ]
then
    echo -n "$pw" | ansible-vault encrypt_string --stdin-name password
else
    echo "$pw"
fi

exit 0
