#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RESULT=0

echo -n Checking for yaml files
YAML=$( find . -name '*.yaml' )
if [ -n "$YAML" ]
then
    echo
    echo "Found files *.yaml (should be *.yml):"
    for f in $YAML
    do
        echo " - $f"
    done
    RESULT=1
else
    echo OK
fi
echo

# magick to use multiple CPUs for checking
if [ -e "/proc/cpuinfo" ]
then
    numcpu=$( grep "^processor" /proc/cpuinfo | wc -l )
elif [ -x "/usr/sbin/sysctl" ]
then
    numcpu=$( /usr/sbin/sysctl -n hw.logicalcpu )
else
    echo "Woops, only Linux and MacOS are supported"
    exit 1
fi
numj2=$(  find . -name '*.j2'  | wc -l )
numyml=$( find . -name '*.yml' | wc -l )

maxj2=$(  expr $numj2  / $numcpu + 1 )
maxyml=$( expr $numyml / $numcpu + 1 )

echo "Checking jinja2 files "
find . -name '*.j2'  -print0 | xargs -0 -n${maxj2}  -P${numcpu} ${DIR}/syntax-jinja || RESULT=1
echo

echo "Checking yml syntax "
find . -name '*.yml' -print0 | xargs -0 -n${maxyml} -P${numcpu} ${DIR}/syntax-yml   || RESULT=1
echo

echo -n "Running yamllint... "
find . -name '*.yml' -print0 | xargs -0 -n${maxyml} -P${numcpu} yamllint            || RESULT=1
echo done

echo -n "Running Ansible check... "
ansible-playbook --syntax-check provision.yml \
    -i ./environments/vm/inventory --extra-vars="secrets_file=environments/vm/secrets/all.yml" || RESULT=1

exit $RESULT

