#!/usr/bin/python
from __future__ import print_function
import yaml
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

filename = sys.argv[1]
print("Checking {}... ".format(filename), end='')

try:
	with open(filename) as y:
		yaml.safe_load(y.read())
except Exception as e:
	print("failed: {}".format(e))
	exit(1)

print("ok")
sys.exit(0)

