#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RESULT=0

echo -n Checking for yaml files
YAML=$( find . -name '*.yaml' )
if [ -n "$YAML" ]
then
    echo
    echo "Found files *.yaml (should be *.yml):"
    for f in $YAML
    do
        echo " - $f"
    done
    RESULT=1
else
    echo OK
fi
echo

echo "Checking jinja2 files "
find . -name '*.j2'  -print0 | xargs -0 ${DIR}/syntax-jinja || RESULT=1
echo

echo "Checking yml syntax "
find . -name '*.yml' -print0 | xargs -0 ${DIR}/syntax-yml   || RESULT=1
echo

echo -n "Running yamllint... "
find . -name '*.yml' -print0 | xargs -0 yamllint            || RESULT=1
echo done

exit $RESULT

