#!/bin/bash
set -e

if ! test -e .travis.yml
then
    echo Run this script from the SCZ-deploy root dir
    exit 2
fi

# activate correct python virtualenv
source $HOME/virtualenv/python3.6/bin/activate

echo '===================================================='
echo '== Running Syntax Check'
echo '===================================================='
./scripts/syntax-check

echo '===================================================='
echo '== Starting deploy (run 1)'
echo '===================================================='
./start-vm --provider docker
echo

# run second time, to check if reeantrace works ok
echo '===================================================='
echo '== Starting deploy (run 2)'
echo '===================================================='
export REEANTRANT=1
./start-vm
echo

# check if the second run didn't give (too many) "changed"-states
echo '===================================================='
echo '== Running idempotency check...'
echo '===================================================='
python ./scripts/check-idempotency-status

exit 0

