#!/bin/bash
set -e

if ! test -e .travis.yml
then
    echo Run this script from the SCZ-deploy root dir
    exit 2
fi


./scripts/syntax-check

./start-vm --provider docker

# run second time, to check if reeantrace works ok
export REEANTRANT=1
./start-vm

# check if the
echo Running idempotency check...
./scripts/check-idempotency-status

exit 0

