---
- name: "enable monitor job"
  systemd:
    name: "sram-monitor@{{item}}.timer"
    enabled: true
    state: "started"
    daemon_reload: true
  loop:
    - "chrome"
    - "firefox"

- name: "restart zabbix-agent"
  systemd:
    name: "zabbix-agent2.service"
    state: "restarted"
