---
ansible_ssh_common_args: '-o StrictHostKeyChecking=false'
# note: {{playbook_dir}} would probably be nicer, but it turns out that that is
# a relative path, which ssh doesn't understand
ansible_ssh_user: "vagrant"
ansible_ssh_private_key_file: "{{inventory_dir}}/../../.vagrant/id_rsa"

secrets_file: "environments/vm/secrets/all.yml"
secrets_users_file: "environments/vm/secrets/users.yml"

admin_email: "admin@{{base_domain}}"

servers:
  dns:
    - 8.8.8.8
  search:
    - vm.scz-vm.net
  ntp:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
    - 3.pool.ntp.org

fake_hostnames: true
use_logserver: false

enable_https: true
http_proto: "http{% if enable_https %}s{% endif %}"

# onderstaande is breekbaar; ansible_default_ipv4 kan best een dhcp-ip zijn
# dat niet in de inventory is gedefinieerd. (afhankelijk van je configuratie
# van libvirt etc)
iprange:
  vm:
    - "172.20.1.0/24"
    - "10.0.0.0/16"
    - "192.168.121.0/24"
  bastion:    "172.20.1.1"
  lb:         "172.20.1.24"
  comanage:   "172.20.1.21"
  mgnt:       "172.20.1.0/24"

mail:
  relay_host: "172.20.1.1"
  relay_to: "outgoing.{{base_domain}}"
  relay_for:
    - "{{iprange.mgnt}}"
  domain: "{{base_domain}}"
  admin_address: "root@{{base_domain}}"

admin:
  fn: "B."
  sn: "Baas"
  eppn: "admin@{{base_domain}}"
  email: "{{admin_email}}"
  sho: "{{base_domain}}"


# poor man's user management
root:
  pw_hash: "$6$rounds=500000$AtgwpGVMAm0fyIf$g4JqeEu8O//KsklaqIEJX6UnQgEtrMTrZdNcp/v/O/G75BjISGZINC\
            rJ0JREkKficMZV5IsdshT9cVACb0cxR1"
users:
  - name: SCZ
    uid: scz
    groups: ['scz','sudo_test','sudo_mgnt','systemd-journal']
    # password 'scz'
    pw_hash: "$6$rounds=500000$OOIfLX7bEQus$krZ/mSucwYN5dK25FlrvxmkMfUa4R585tXwihZFDWbXUVSJXymIeJpq\
              pRvP88TEgaNAXrKMD9qbWYvnSLeDOe."
    sshkey: ""

mysql_users:
  - name: scz_ro
    hash: "*8E0BCAC26AAA6C79D77D9F8FDDA6DCDD03BDB93F"
    priv: "*.*:ALL,GRANT"
    host: localhost
  - name: scz_ro
    hash: "*8E0BCAC26AAA6C79D77D9F8FDDA6DCDD03BDB93F"
    priv: "*.*:ALL,GRANT"
    host: "%"

firewall_v4_incoming:
  - { name: bastion,  src: "{{iprange.bastion}}", dport: "22,80,443", proto: tcp }
  - { name: vnet,     src: "{{iprange.vm}}",      dport: "22,80,443", proto: tcp }

backup_base: "/opt/backups"
backup_runparts: "{{backup_base}}/run.d"

# LDAP definition is here, because we need it in both the Ldap and Comanage groups
ldap:
  basedn: "dc=scz,dc=vnet"
  o:      "SCZ"
  binddn: "cn=John Doe,dc=scz,dc=vnet"

client_ldap:
  basedn: "dc=client,dc=vnet"
  o:      "Client"
  binddn: "cn=admin,dc=client,dc=vnet"

clients_ldap:
  basedn: "dc=clients,dc=vnet"
  o:      "Clients"
  binddn: "cn=admin,dc=clients,dc=vnet"


# Comanage-Proxy database configuration is here, because it is needed in both the
# Proxy and Comanage groups.
comanage_proxy_db: "{{ groups['proxy'][0] }}"
comanage_proxy_db_user: "scz"
comanage_proxy_db_name: "cotosa"
comanage_proxy_attribute: "cmuid"

php_debug: true
php_xdebug_host: "{{iprange.bastion}}"

sbs_client_id: sbs-server
sbs_base_url: "https://{{hostnames.sbs}}/"

# Docker ports
docker_ports:
  sbs: 8321

# Enable SBS deploy
sbs_enabled: true
sbs_api_url: "{{ http_proto }}://{{ hostnames.sbs }}/"

# No Zabbix on VM/Travis
zabbix_enabled: false

