---
- name: Ensure that openjdk-8-jdk is installed
  apt:
    name:
      - openjdk-8-jdk

- name: Add Elesticsearch key
  apt_key:
    data: "{{ lookup('file', 'GPG-KEY-elasticsearch') }}"

- name: Add Elasticsearch repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
    update_cache: yes

- name: Ensure that packages are installed
  apt:
    name: "{{ item }}"
    install_recommends: no
  with_items:
    - elasticsearch
    - logstash
    - kibana
    - collectd
    - elasticsearch-curator

- name: Ensure Elasticsearch data directory exists
  file: path=/var/elasticsearch state=directory mode=0750 owner=elasticsearch

- name: Copy elasticsearch jvm.options file
  copy:
    src: jvm.options
    dest: /etc/elasticsearch/jvm.options
  notify: restart elasticsearch

- name: Copy elasticsearch configuration file
  copy:
    src: "{{ item }}"
    dest: "/etc/elasticsearch/{{ item }}"
  with_items:
    - elasticsearch.yml
    - curator.yml
    - curator_actions.yml
  notify: restart elasticsearch

- name: Copy logstash configuration file
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
  notify: restart logstash

- name: Copy kibana configuration file
  copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
  notify: restart kibana

- name: Disable collectd service
  systemd: name=collectd state=stopped enabled=no
