---
- name: Ensure that packages are installed
  apt:
    name:
      - xalan
      - wget
      - xmlsec1
    state: present

- name: Create directories
  file:
    path: "{{ item }}"
    state: "directory"
    mode: "0755"
  with_items:
    - "{{ metadata_project_dir }}"
    - "{{ metadata_documentroot }}"

- name: Copy metadata nginx configuration
  template:
    src: metadata.nginx.j2
    dest: "/etc/nginx/sites-available/metadata"
    mode: 0755
  notify: restart nginx

- name: Create symlink to metadata in /etc/nginx/sites-enabled
  file:
    src: "/etc/nginx/sites-available/metadata"
    dest: "/etc/nginx/sites-enabled/00-metadata"
    state: link
  notify: restart nginx

- name: Install index page
  template:
    src: "index.html.j2"
    dest: "{{metadata_documentroot}}/index.html"
    mode: 0644

- name: Install logo
  copy:
    src: "{{ item }}"
    dest: "{{metadata_documentroot}}/"
    mode: "0644"
  with_items:
    - "surf.svg"
    - "surf.png"

- name: Remove obsolete files
  file:
    path: "{{metadata_documentroot}}/{{item}}"
    state: "absent"
  with_items:
    - "Light-Bulb_icon_by_Till_Teenck.svg"
    - "Light-Bulb_icon_by_Till_Teenck_1000px.png"
    - "Light-Bulb_icon_by_Till_Teenck_200px.png"
    - "proxy_idp.xml"
    - "proxy_sp.xml"
    - "sc_edugain.xml"
    - "sc_edugain_idps.xml"
    - "sc_edugain_idps_nologo.xml"
    - "sc_edugain_idps_nologo_nohide.xml"
    - "sc_edugain_idps_nologo_nohide_nosc.xml"
