# installs nginx to handle static file and reverse-proxy chrerrypy
---
- name: install NGINX
  apt:
    name: nginx
    state: present

- name: remove default NGINX sites
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: install NGINX config file
  template:
    src: nginx-pam.conf.j2
    dest: /etc/nginx/sites-enabled/00-pam.conf
  notify: restart nginx

- name: enable NGINX
  service:
    name: nginx
    state: started
    enabled: true

