---
- name: "enable monitor job"
  systemd:
    name: "sram-ldapmonitor.timer"
    enabled: true
    state: "restarted"
    daemon_reload: true

- name: "restart zabbix-agent"
  systemd:
    name: "zabbix-agent2.service"
    state: "restarted"
