---
- name: create ssl directory
  file:
    dest: "{{cert_dir}}"
    state: "directory"
    mode: "0700"

- name: write secret key
  copy:
    content: "{{https_cert.key}}"
    dest: "{{cert_dir}}/key.pem"
    mode: "0600"
    owner: "root"
  no_log: "{{sram_ansible_nolog}}"
  notify: "cert updated"

- name: write certificate
  copy:
    content: "{{https_cert.cert}}"
    dest: "{{cert_dir}}/cert.pem"
    mode: "0600"
    owner: "root"
  notify: "cert updated"

- name: write chain
  copy:
    content: "{{https_cert.chain}}"
    dest: "{{cert_dir}}/chain.pem"
    mode: "0600"
    owner: "root"
  notify: "cert updated"

- name: write fullchain
  copy:
    content: "{{https_cert.cert}}\n{{https_cert.chain}}"
    dest: "{{cert_dir}}/fullchain.pem"
    mode: "0600"
    owner: "root"
  notify: "cert updated"

- name: write priv+fullchain
  copy:
    content: |
      {{https_cert.key}}
      {{https_cert.cert}}
      {{https_cert.chain}}
    dest: "{{cert_dir}}/priv+fullchain.pem"
    mode: "0600"
    owner: "root"
  no_log: "{{sram_ansible_nolog}}"
  notify: "cert updated"

- name: make links for all hosts
  file:
    dest: "{{cert_dir}}/{{item}}"
    state: "link"
    src: "./"
  with_items: '{{loadbalancer|map(attribute="hostname")|list}}'
  notify: "cert updated"

