---
- name: restart sshd
  service:
    name: "sshd"
    state: "restarted"
  when:
    - 'environment_name!="vm"'
    - 'environment_name!="ci"'


- name: reload sysctl settings
  systemd:
    name: "systemd-sysctl.service"
    state: "restarted"
  when:
    - 'environment_name!="vm"'
    - 'environment_name!="ci"'
