---
- name: Ensure that packages are installed
  apt:
    name:
      - libapache2-mod-auth-openidc
    state: present

#https://github.com/zmartzone/mod_auth_openidc/issues/299
#https://github.com/zmartzone/mod_auth_openidc/issues/308
- name: Globally disable apache2 OIDC module
  apache2_module:
    state: absent
    name: "{{item}}"
    ignore_configcheck: true
  notify: restart Apache
  with_items:
    - auth_openidc_

- name: Create new SP test root index.php
  template:
    src: sp_index.php.j2
    dest: /var/www/html/index.php
    mode: 0644

- name: Create OIDC RP test dir
  file:
    path: "/var/www/html/oidc"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: Create new OIDC RP test root index.php
  copy:
    src: oidc_index.php
    dest: /var/www/html/oidc/index.php
    mode: 0644

- name: Add websites
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ item }}.conf"
    mode: 0644
  with_items:
    - oidc
  notify: restart Apache

- name: Enable websites
  file:
    src: "/etc/apache2/sites-available/{{ item }}.conf"
    dest: "/etc/apache2/sites-enabled/00-{{ item }}.conf"
    state: link
  with_items:
    - oidc
  notify: restart Apache

