---
name: Project automation

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - closed

jobs:
  project_management:
    uses: SURFscz/SRAM-deploy/.github/workflows/project.yml@main
    with:
      event: ${{ github.event_name }}
      action: ${{ github.event.action }}
    secrets: inherit

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
