---
name: Project automation (Generic)

# reusable workflow, call this like:
# jobs:
#   project_management:
#     uses: SURFscz/SRAM-deploy/.github/workflows/project.yml@main
#     with:
#       event: ${{ github.event_name }}
#       action: ${{ github.event.action }}
#     secrets: inherit

on:
  workflow_call:
    inputs:
      event:
        required: true
        type: string
      action:
        required: true
        type: string
      state_reason:
        required: false
        type: string

env:
  organization: ${{ github.repository_owner }}
  project_id: 5
  gh_app_id: 228588
  gh_app_inst_id: 28270300
  gh_app_secret: ${{ secrets.SRAM_PROJECT_SECRET }}

jobs:
  issue_project_management:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "event: ${{ inputs.event }}"
          echo "action: ${{ inputs.action }}"
          echo "state_reason: ${{ inputs.state_reason }}"
        if: true
      - name: Add issue to project
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_app_ID: ${{ env.gh_app_id }}
          gh_app_installation_ID: ${{ env.gh_app_inst_id }}
          gh_app_secret_key: ${{ env.gh_app_secret }}
          organization: ${{ env.organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: New
        if: >
          inputs.event == 'issues'
          && (inputs.action == 'opened' || inputs.action == 'reopened')
      - name: Set
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_app_ID: ${{ env.gh_app_id }}
          gh_app_installation_ID: ${{ env.gh_app_inst_id }}
          gh_app_secret_key: ${{ env.gh_app_secret }}
          organization: ${{ env.organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Done
        if: >
          inputs.event == 'issues'
          && inputs.action == 'closed'
          && inputs.state_reason == 'not_planned'
