---
name: CI-Runner

on:
  # Triggers the workflow manually
  workflow_dispatch:
    inputs:
      foobar:
        description: 'my Foobar'
        required: true
        default: 'myBar'

jobs:
  test:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      # Decrypt secret
      - name: Copy secret
        shell: bash
        env:
          secret_vm: ${{ secrets.SECRET_VM }}
        run: "echo $secret_vm > secret_vm"

      - name: Hello World
        run: |
          touch HelloWorld
          echo "Hello world ${{ github.event.inputs.foobar }}" >> HelloWorld

      - name: Stop running dockers
        run: |
          ./docker/docker-compose.yml.py --ci > ./docker/docker-compose-ci.yml
          docker-compose -f docker/docker-compose-ci.yml stop

      - name: Start CI env
        run: |
          ./start-ci

      - name: Bootstrap virtualenv in ci-runner
        run: |
          python3 -m virtualenv --python=python3 ci-runner
          ci-runner/bin/pip install -r ci-runner/requirements.txt

      - name: Run tests
        run: |
          ci-runner/bin/behave ci-runner/features/
